chef/cookstyle

config/cookstyle.yml

Disable Style/AsciiComments and comment other recent additions

---

config/cookstyle.yml
lib/cookstyle/version.rb

I rearranged the file a bit and added comments explaining why things
made sense.

Add new cops from 0.46 and bump to 1.0.0

---

CHANGELOG.md
config/cookstyle.yml
lib/cookstyle/version.rb

Properly disable Lint/AmbiguousRegexpLiteral

---

config/cookstyle.yml

Disable .zero? which is slower and introduces regressions

---

config/cookstyle.yml
config/cookstyle_base.yml

See #28 for discussion.
Signed-off-by: Roland Moriz <roland@moriz.de>

Disable Style/DoubleNegation (#28)

---

CHANGELOG.md
config/cookstyle.yml
lib/cookstyle/version.rb

Replaces PR #16. I ran into weird errors when rebasing #16 and trying to push so instead of messing with the original feature branch I just created a new one with the necessary changes. I wasn't sure whether I should go ahead and do a CHANGELOG as I think part of the problem arrives when fussing with the CHANGELOG but as this is straightforward maybe this will get pulled in quickly?

Disable Style/GuardClause

---

CHANGELOG.md

I'll release this on 5-7. No one wants a major release on Friday at 5pm

Add the changelog for 3.0.

---

cookstyle.gemspec

Add back the gemspec and gemfile for appbundler

---

.expeditor/verify.pipeline.yml
.travis.yml
README.md

Fix buildkite pipeline setup

---

lib/rubocop/cop/chef/file_mode.rb
lib/rubocop/cop/chef/service_resource.rb
lib/rubocop/cop/chef/tmp_path.rb

Without this these will not trigger.

Fix node matchers to properly trigger

---

config/cookstyle.yml
lib/rubocop/cop/chef/berksfile_source.rb

Add cop to detect old Berkfile sources

---

config/cookstyle.yml
lib/rubocop/cop/chef/node_normal.rb
lib/rubocop/cop/chef/node_normal_unless.rb

these will have to perpetually warn, they cannot be autofixed.

Add Chef/NodeNormal & Chef/NodeNormalUnless for node.normal/node.normal_unless usage

---

lib/rubocop/cop/chef/why_run_supported_true.rb

This detects why_run being set to true in resources and removes those occurrences

Add Chef/WhyRunSupportedTrue

---

.expeditor/verify.pipeline.yml

Let's make sure it runs on Windows as well.

Test the cookstyle binary on Windows in Buildkite

---

config/cookstyle.yml
lib/rubocop/cop/chef/build_essential.rb

This migrates users from the build-essential recipe to the resource

Add new UseBuildEssentialResource cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/epic_fail.rb

Detects usage of the deprecated epic_fail method

Add Chef/EpicFail

---

config/cookstyle.yml
lib/rubocop/cop/chef/name_property_and_required.rb
spec/rubocop/cop/chef/name_property_and_required_spec.rb

This detects when a resource property is both required and a name
property

Add Chef/NamePropertyIsRequired cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/cb_depends_on_self.rb
lib/rubocop/cop/chef/correctness/metadata_missing_name.rb
spec/rubocop/cop/chef/correctness/cb_depends_on_self_spec.rb
spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb

Move two more Foodcritic alerts over to Cookstyle

Add Chef/CookbooksDependsOnSelf and Chef/MetadataMissingName

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/invalid_license_string.rb
spec/rubocop/cop/chef/correctness/invalid_license_string_spec.rb

Detect non-SPDX licenses and auto correct some of the more common ones.

Add Chef/InvalidLicenseString cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/respond_to_metadata.rb
spec/rubocop/cop/chef/deprecation/respond_to_metadata_spec.rb

Detect the legacy usage of .respond_to?(:whatever) in metadata.rb

Add Chef/RespondToInMetadata cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb
spec/rubocop/cop/chef/correctness/invalid_platform_metadata_spec.rb

Detect invalid platforms and autocorrect some common typos

Add Chef/InvalidPlatformMetadata cop

---

lib/rubocop/cop/chef/deprecation/node_set.rb
lib/rubocop/cop/chef/deprecation/node_set_unless.rb
spec/rubocop/cop/chef/deprecation/node_set_spec.rb
spec/rubocop/cop/chef/deprecation/node_set_unless_spec.rb

fix node.set/set_unless autocorrects to not break ChefSpec tests

---

lib/rubocop/cop/chef/deprecation/node_set.rb
lib/rubocop/cop/chef/deprecation/node_set_unless.rb

i_have_no_idea_what_im_doing_dog.jpg

don't need the ${}'s guess that is grouping

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/resource_set_or_return.rb
spec/rubocop/cop/chef/modernize/resource_set_or_return_spec.rb

Detect use of set_or_return being used where a property would work better.

Add Chef/SetOrReturnInResources cop

---

RELEASE_NOTES.md

Add the notes for this release.

Add Cookstyle 5.2 release notes

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/resource_with_attributes.rb
spec/rubocop/cop/chef/modernize/resource_with_attributes_spec.rb

This detects custom resources with attributes instead of properties

Add Chef/CustomResourceWithAttributes cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/apt_default_recipe.rb
lib/rubocop/cop/chef/modernize/windows_default_recipe.rb
lib/rubocop/cop/chef/modernize/yum_dnf_compat_recipe.rb
spec/rubocop/cop/chef/modernize/apt_default_recipe_spec.rb
spec/rubocop/cop/chef/modernize/windows_default_recipe_spec.rb
spec/rubocop/cop/chef/modernize/yum_dnf_compat_recipe_spec.rb

Chef/IncludingAptDefaultRecipe
Chef/IncludingWindowsDefaultRecipe
Chef/IncludingYumDNFCompatRecipe

Add 3 new cops for detecting legacy recipes being included

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/minitest_handler_usage.rb
lib/rubocop/cop/chef/modernize/windows_version_helper.rb
lib/rubocop/cop/chef/modernize/windows_zipfile.rb
spec/rubocop/cop/chef/modernize/minitest_handler_usage_spec.rb
spec/rubocop/cop/chef/modernize/windows_version_helper_spec.rb
spec/rubocop/cop/chef/modernize/windows_zipfile_spec.rb

Add three more cops for modernizing cookbooks

Add Chef/MinitestHandlerUsage Chef/WindowsVersionHelper Chef/WindowsZipfileUsage

---

RELEASE_NOTES.md

Document the new cops and improvements that were made.

Add Cookstyle 5.3 release notes

---

lib/rubocop/cop/chef/correctness/cb_depends_on_self.rb
lib/rubocop/cop/chef/correctness/property_with_default_and_required.rb
spec/rubocop/cop/chef/correctness/cb_depends_on_self_spec.rb

Spell out when this will blow up in your face.

Improve error messages in CookbooksDependsOnSelf & PropertyWithRequiredAndDefault

---

spec/rubocop/cop/chef/correctness/property_with_default_and_required_spec.rb

Add spec for Chef/PropertyWithRequiredAndDefault

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/chef_rest.rb
spec/rubocop/cop/chef/deprecation/chef_rest_spec.rb

Detect the code we removed in Chef 13.

Add Chef/UsesChefRESTHelpers

---

RELEASE_NOTES.md
lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb
lib/rubocop/cop/chef/correctness/name_property_and_required.rb
lib/rubocop/cop/chef/correctness/node_save.rb

Add the release notes for this week's release.

Add release notes for Cookstyle 5.5

---

RELEASE_NOTES.md
config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/chocolatey_package_uninstall_action.rb
lib/rubocop/cop/chef/deprecation/launchd_deprecated_hash_property.rb
spec/rubocop/cop/chef/deprecation/attribute_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/chocolatey_package_uninstall_action_spec.rb
spec/rubocop/cop/chef/deprecation/conflicts_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/depends_compat_resource_spec.rb
spec/rubocop/cop/chef/deprecation/deprecated_mixins_spec.rb
spec/rubocop/cop/chef/deprecation/epic_fail_spec.rb
spec/rubocop/cop/chef/deprecation/launchd_deprecated_hash_property_spec.rb
spec/rubocop/cop/chef/deprecation/long_description_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/provides_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/replaces_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/suggests_metadata_spec.rb
spec/rubocop/cop/chef/deprecation/user_supports_property_spec.rb
spec/rubocop/cop/chef/modernize/defines_chefspec_matchers_spec.rb
spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb
spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
spec/rubocop/cop/chef/modernize/whyrun_supported_true_spec.rb
spec/rubocop/cop/chef/modernize/windows_default_recipe_spec.rb
spec/rubocop/cop/chef/modernize/xml_ruby_recipe_spec.rb
spec/rubocop/cop/chef/modernize/yum_dnf_compat_recipe_spec.rb
tasks/cops_documentation.rake

This matches what I wrote in the release notes already. There's a few more I could add autocorrection to, but I'll do that for 5.6

Add additional autocorrect and improve autocorrection testing

---

config/cookstyle.yml
lib/rubocop/cop/chef/style/use_platform_helpers.rb
spec/rubocop/cop/chef/style/use_platform_helpers_spec.rb

Move people towards our platform? and platform_family? helpers to simplify the platform checks in their recipes / resources.

Add ChefStyle/UsePlatformHelpers cop

---

config/cookstyle.yml
docs/cops.md
docs/cops_chefdeprecations.md
docs/cops_chefmodernize.md
docs/cops_chefstyle.md
lib/rubocop/cop/chef/modernize/cron_manage_resource.rb
lib/rubocop/cop/chef/modernize/depends_zypper_cookbook.rb
lib/rubocop/cop/chef/modernize/execute_tzutil.rb
lib/rubocop/cop/chef/modernize/macos_user_defaults.rb
lib/rubocop/cop/chef/modernize/openssl_rsa_key_resource.rb
lib/rubocop/cop/chef/modernize/openssl_x509_resource.rb
lib/rubocop/cop/chef/modernize/osx_config_profile_resource.rb
lib/rubocop/cop/chef/modernize/systctl_param_resource.rb
lib/rubocop/cop/chef/modernize/zypper_repo.rb
spec/rubocop/cop/chef/modernize/cron_manage_resource_spec.rb
spec/rubocop/cop/chef/modernize/depends_zypper_cookbook_spec.rb
spec/rubocop/cop/chef/modernize/execute_tzutil_spec.rb
spec/rubocop/cop/chef/modernize/macos_user_defaults_spec.rb
spec/rubocop/cop/chef/modernize/openssl_rsa_key_resource_spec.rb
spec/rubocop/cop/chef/modernize/openssl_x509_resource_spec.rb
spec/rubocop/cop/chef/modernize/osx_config_profile_resource_spec.rb
spec/rubocop/cop/chef/modernize/systctl_param_resource_spec.rb
spec/rubocop/cop/chef/modernize/zypper_repo_spec.rb

ChefModernize/CronManageResource
ChefModernize/UsesZypperRepo
ChefModernize/DependsOnZypperCookbook
ChefModernize/ExecuteTzUtil
ChefModernize/OpensslRsaKeyResource
ChefModernize/OpensslX509Resource
ChefModernize/OsxConfigProfileResource
ChefModernize/SysctlParamResource
ChefModernize/MacOsXUserdefaults
Tests incoming

Add 9 new cops for updating to resources in Chef Infra Client 

---

lib/rubocop/cop/chef/modernize/cron_manage_resource.rb
lib/rubocop/cop/chef/modernize/macos_user_defaults.rb
lib/rubocop/cop/chef/modernize/openssl_rsa_key_resource.rb
lib/rubocop/cop/chef/modernize/openssl_x509_resource.rb
lib/rubocop/cop/chef/modernize/osx_config_profile_resource.rb
lib/rubocop/cop/chef/modernize/systctl_param_resource.rb
lib/rubocop/cop/chef/modernize/zypper_repo.rb
spec/rubocop/cop/chef/modernize/cron_manage_resource_spec.rb
spec/rubocop/cop/chef/modernize/macos_user_defaults_spec.rb
spec/rubocop/cop/chef/modernize/openssl_rsa_key_resource_spec.rb
spec/rubocop/cop/chef/modernize/openssl_x509_resource_spec.rb
spec/rubocop/cop/chef/modernize/osx_config_profile_resource_spec.rb
spec/rubocop/cop/chef/modernize/systctl_param_resource_spec.rb
spec/rubocop/cop/chef/modernize/zypper_repo_spec.rb

Add autocorrection to some of the new cops.

Add autocorrects to 7 cops

---

RELEASE_NOTES.md
config/cookstyle.yml
lib/rubocop/cop/chef/modernize/openssl_x509_resource.rb
spec/rubocop/cop/chef/modernize/openssl_x509_resource_spec.rb

Add release notes for 5.6

---

lib/rubocop/cop/chef/correctness/block_guard_clause_string_only.rb
lib/rubocop/cop/chef/correctness/default_maintainer_metadata.rb
lib/rubocop/cop/chef/correctness/invalid_license_string.rb
lib/rubocop/cop/chef/correctness/metadata_missing_name.rb
spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb

Let's see if the docs are auto generated when this PR merges

Reformat text comments for better docs

---

lib/rubocop/cop/chef/deprecation/long_description_metadata.rb

I have no idea what I was thinking when I wrote this, but it checks the same thing twice.

Simplify ChefDeprecations/LongDescriptionMetadata

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/empty_metadata_field.rb
spec/rubocop/cop/chef/correctness/empty_metadata_field_spec.rb

Metadata shouldn't include empty fields

Add ChefCorrectness/EmptyMetadataField cop

---

RELEASE_NOTES.md

Add the release notes for 5.8 so we can ship

Add Cookstyle 5.8 release notes

---

cookstyle.gemspec

Use the description from the readme so that our description on Rubygems
matches what we can do now.

Add a better description to the gem

---

RELEASE_NOTES.md

This is a small release, but we should get it into the DK 4 release.

Add 5.9 Release Notes

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
spec/rubocop/cop/chef/correctness/incorrect_library_innjection_spec.rb

Add ChefCorrectness/IncorrectLibraryInjection cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/effortless/node_environment.rb
lib/rubocop/cop/chef/effortless/node_policygroup.rb
lib/rubocop/cop/chef/effortless/node_roles.rb
spec/rubocop/cop/chef/effortless/node_environment_spec.rb
spec/rubocop/cop/chef/effortless/node_policygroup_spec.rb
spec/rubocop/cop/chef/effortless/node_roles_spec.rb

A few more disabled by default cops to help folks to upgrade.

Add 3 new cops for migrating to Effortless

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/deprecated_yum_repository_properties.rb
spec/rubocop/cop/chef/deprecation/deprecated_yum_repository_properties_spec.rb

Detect yum cookbook pre-3.0 properties.
There's 76 occurrences of this on the Supermarket.

Add ChefDeprecations/LegacyYumRepositoryProperties

---

RELEASE_NOTES.md

Add Cookstyle 5.10 release notes

---

RELEASE_NOTES.md

Add two additional cops to the 5.10 release notes

---

lib/rubocop/cop/chef/effortless/node_environment.rb
spec/rubocop/cop/chef/effortless/node_environment_spec.rb

This resolves https://github.com/chef/cookstyle/issues/205

Expand the detection of node.chef_environment

---

CHANGELOG.md
config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/poise_archive.rb
lib/rubocop/cop/chef/modernize/definitions.rb
spec/rubocop/cop/chef/deprecation/poise_archive_spec.rb
spec/rubocop/cop/chef/modernize/definitions_spec.rb
tasks/cops_documentation.rake

Add additional cops to detect things we're seeing folks struggling with.
Closes: https://github.com/chef/cookstyle/issues/350

Add new poise_archive cop and definition cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/effortless/search_for_environments_or_roles.rb
spec/rubocop/cop/chef/effortless/search_for_environments_or_roles_spec.rb

This detects search queries that contain roles or environments

Add ChefEffortless/SearchForEnvironmentsOrRoles

---

RELEASE_NOTES.md

Add 5.11 release notes

---

.expeditor/build_docs.sh
README.md
tasks/cops_documentation.rake

Let's brag a little. We did this with Foodcritic

Update the readme cop count on each merge

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/if_provides_default_action.rb
spec/rubocop/cop/chef/modernize/if_provides_default_action_spec.rb

Detect some very legacy guards in resources.

Add ChefModernize/IfProvidesDefaultAction cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/zipfile_resource.rb
spec/rubocop/cop/chef/modernize/zipfile_resource_spec.rb

Another cop to detect legacy compression resources in community
cookbooks
Fixes #380 

Add ChefModernize/ZipfileResource

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/cheffile.rb
spec/rubocop/cop/chef/deprecation/cheffile_spec.rb
spec/rubocop/cop/chef/effortless/Berksfile_spec.rb

Alerts if there's a Cheffile in the cookbook. I'm not sure how to test this with out current framework. I'll have to see if Rubocop has anything similar.

Add ChefDeprecations/Cheffile

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/node_deep_fetch.rb
spec/rubocop/cop/chef/deprecation/node_deep_fetch_spec.rb
tasks/cops_documentation.rake

first one for https://github.com/chef/chef-sugar/pull/16

add cops for chef-sugar's node.deep_fetch

---

lib/rubocop/cop/chef/deprecation/run_command_helper.rb
spec/rubocop/cop/chef/deprecation/run_command_helper_spec.rb

Another legacy method from this mixin

Detect run_command_with_systems_locale in ChefDeprecations/UsesRunCommandHelper

---

RELEASE_NOTES.md
config/cookstyle.yml

Add Cookstyle 5.12 release notes

---

README.md

The previous merge of release notes also included a config fix. We need
to trigger a new build to get this release out.

Readme updates to trigger a new build

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/empty_resource_initialize.rb
spec/rubocop/cop/chef/modernize/empty_resource_initialize_spec.rb

Remove initialize methods that aren't doing anything in resources. Helps

Add ChefModernize/EmptyResourceInitializeMethod cop

---

lib/rubocop/cop/chef/deprecation/legacy_notify_syntax.rb
spec/rubocop/cop/chef/deprecation/legacy_notify_syntax_spec.rb

This is probably one of the top 5 crazy autocorrectors we have. I searched through the supermarket to see what potential values could look like so we could make sure it can handle those situations.

Improve auto correction in LegacyNotifySyntax

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/node_set_without_level.rb
spec/rubocop/cop/chef/deprecation/node_set_without_level_spec.rb

Detects cookbooks that won't run on Chef 11+

Add ChefDeprecations/NodeSetWithoutLevel cop

---

.expeditor/verify.pipeline.yml

Add Ruby 2.7 testing in Buildkite

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml

Uses the same script we're using in DK and other projects.

Cache the bundles in S3 to speed up tests

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/chef_rewind.rb
spec/rubocop/cop/chef/deprecation/chef_rewind_spec.rb

Detect the usage of the deprecated chef-rewind gem

Add new ChefDeprecations/ChefRewind cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/chef_gem_nokogiri.rb
spec/rubocop/cop/chef/modernize/chef_gem_nokogiri_spec.rb

Add new ChefModernize/ChefGemNokogiri cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/includes_mixin_shellout.rb
spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb

I meant to track this down before shipping 5.12, but at least we're getting it in.

Improve IncludingMixinShelloutInResources cops message to include Chef Versions

---

cookstyle.gemspec

This will add additional links on Rubygems

Add new rubygems metadata

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/invalid_platform_family_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb
spec/rubocop/cop/chef/correctness/invalid_platform_family_helper_spec.rb
spec/rubocop/cop/chef/correctness/invalid_platform_helper_spec.rb

I've noticed people get these wrong far too often and it will break
cookbooks in really hard to troubleshoot ways.

Add ChefCorrectness/InvalidPlatformHelper and ChefCorrectness/InvalidPlatformFamilyHelper

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/scoped_file_exist.rb
spec/rubocop/cop/chef/correctness/scoped_file_exist_spec.rb

Make sure File.exist? is scoped properly in connditionals

Add ChefCorrectness/ScopedFileExist cop

---

RELEASE_NOTES.md

Add Cookstyle 5.15 release notes

---

lib/cookstyle.rb
lib/rubocop/chef/cookbook_helpers.rb
lib/rubocop/chef/platform_helpers.rb
lib/rubocop/cop/chef/correctness/invalid_platform_family_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb

This will probably include additional helpers in the future, but for now it's these two constants

Move invalid platform constants into a single helper

---

lib/rubocop/chef/platform_helpers.rb

Add more invalid platform families to our helper

---

RELEASE_NOTES.md
config/cookstyle.yml
lib/rubocop/cop/chef/correctness/invalid_value_for_platform_family_helper.rb
lib/rubocop/cop/chef/correctness/invalid_value_for_platform_helper.rb
spec/rubocop/cop/chef/correctness/invalid_value_for_platform_family_helper_spec.rb
spec/rubocop/cop/chef/correctness/invalid_value_for_platform_helper_spec.rb

Catch bogus inputs to these helpers. There's a lot of folks passing bad data here that are not getting the expected behavior out of their code.

Add new platform cops for the value_for_platform / value_for_platform_family helpers

---

config/cookstyle.yml
lib/rubocop/cop/chef/style/unnecessary_platform_case_statement.rb
spec/rubocop/cop/chef/style/unnecessary_platform_case_statement_spec.rb

Make's platform checks significantly simpler and also lets us parse the platforms for correctness in other cops that parse platform? and platform_family? data.

Add ChefStyle/UnnecessaryPlatformCaseStatements

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/invalid_notification_timing.rb
spec/rubocop/cop/chef/correctness/invalid_notification_timing_spec.rb

Add ChefCorrectness/InvalidNotificationTiming cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/style/immediate_notification_timing.rb
spec/rubocop/cop/chef/style/immediate_notification_timing_spec.rb

Add ChefStyle/ImmediateNotificationTiming cop

---

RELEASE_NOTES.md
config/cookstyle.yml
lib/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions.rb
lib/rubocop/cop/chef/redundant/sensitive_property_in_resource.rb
spec/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions_spec.rb
spec/rubocop/cop/chef/redundant/sensitive_property_in_resource_spec.rb

Add ChefRedundantCode/SensitivePropertyInResource cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/malformed_value_for_platform.rb
spec/rubocop/cop/chef/correctness/malformed_value_for_platform_spec.rb

Make sure people are passing things in correctly. A lot of people try to use it like value_for_platform_family and it's not the same.

Add ChefCorrectness/MalformedPlatformValueForPlatformHelper cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/dnf_package_allow_downgrades.rb
spec/rubocop/cop/chef/correctness/dnf_package_allow_downgrades_spec.rb

Add ChefCorrectness/DnfPackageAllowDowngrades

---

RELEASE_NOTES.md

Add 5.16 release notes

---

RELEASE_NOTES.md
lib/rubocop/cop/chef/deprecation/deprecated_platform_methods.rb
spec/rubocop/cop/chef/deprecation/deprecated_platform_methods_spec.rb

Also improve warning message / docs for ChefDeprecations/DeprecatedPlatformMethods

Add additional release notes for 5.16

---

config/cookstyle.yml

These were disabled by mistake
ChefModernize/ExecuteScExe
ChefModernize/WindowsScResource
ChefModernize/ExecuteSleep

Enable several cops that were accidently disabled

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/dsl_include_in_resource.rb
spec/rubocop/cop/chef/modernize/dsl_include_in_resource_spec.rb

Remove includes we don't need on Chef 12.4+

Add ChefModernize/DslIncludeInResource

---

lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb
spec/rubocop/cop/chef/correctness/invalid_platform_metadata_spec.rb

This is the more common way that people pass it.

Handle supports metadata in an array

---

lib/rubocop/cop/chef/redundant/name_property_and_required.rb
lib/rubocop/cop/chef/redundant/property_with_default_and_required.rb
spec/rubocop/cop/chef/redundant/property_with_default_and_required_spec.rb

Simplify logic by using matchers
Add autocorrection where possible
PropertyWithRequiredAndDefault now detects in attributes

Improve property cops

---

RELEASE_NOTES.md

This should be good to ship once we have these ready

Add 5.18 release notes

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/execute_sysctl.rb
spec/rubocop/cop/chef/modernize/execute_sysctl_spec.rb

Detect when someone is basically recreating the sysctl resource in their own cookbook.

Add ChefModernize/ExecuteSysctl cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/redundant/grouping_metadata.rb
spec/rubocop/cop/chef/redundant/grouping_metadata_spec.rb

I missed this obscure unused metadata

Add ChefRedundantCode/GroupingMetadata

---

lib/rubocop/cop/chef/deprecation/user_supports_property.rb
spec/rubocop/cop/chef/deprecation/user_supports_property_spec.rb

Make sure we can auto-correct these as well.

Handle user resource supports with hash rockets

---

RELEASE_NOTES.md

Add 5.19 release notes

---

config/cookstyle.yml
lib/rubocop/cop/chef/style/chef_whaaat.rb

Yes, this is somewhat a joke. No it will not be enabled by default.

Add Style/ChefWhaaat cop

---

lib/rubocop/cop/chef/modernize/libarchive_file.rb
spec/rubocop/cop/chef/modernize/libarchive_file_spec.rb

Detect the notifications now and autocorrect the whole thing

Add autocorrect to libarchive_file resources

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/deprecated_chefspec_platform.rb
spec/rubocop/cop/chef/deprecation/deprecated_chefspec_platform_spec.rb

Add ChefDeprecations/DeprecatedChefSpecPlatform

---

RELEASE_NOTES.md

Add release notes for 5.20

---

config/cookstyle.yml

This is a breaking rule that we should not be using

Disable Style/ModuleFunction

---

config/cookstyle.yml

Otherwise we get config warnings

Remove the duplicate Style/ModuleFunction config

---

config/cookstyle.yml

This will greatly reduce the amount of manual work necessary to get a
cookbook to pass.

Autocorrect Layout/EndAlignment and Layout/DefEndAlignment

---

RELEASE_NOTES.md
lib/rubocop/cop/chef/style/unnecessary_os_check.rb

Add release notes for 5.21

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/windows_feature_servermanagercmd.rb
spec/rubocop/cop/chef/deprecation/windows_feature_servermanagercmd_spec.rb

Detect the old install_method value that is no longer accepted.

Add ChefDeprecations/WindowsFeatureServermanagercmd

---

RELEASE_NOTES.md

Add Cookstyle 5.22 release notes

---

.expeditor/config.yml
README.md

Move this project under the Chef Infra project

Move Cookstyle to the Chef Infra project

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/chef_application_fatal.rb
spec/rubocop/cop/chef/correctness/chef_application_fatal_spec.rb

There's over 500 of these on the Supermarket and they cause tons of problems in cookbooks plus they're more complex than just a simple raise.

Add ChefCorrectness/ChefApplicationFatal cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/provides_initializer.rb
spec/rubocop/cop/chef/modernize/provides_initializer_spec.rb

Move HWRPs closer to standard DSL driven custom resources

Add ChefModernize/ProvidesFromInitialize cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/deprecated_windows_version_check.rb
spec/rubocop/cop/chef/deprecation/deprecated_windows_version_check_spec.rb

This checks for the EOL windows version check

Add ChefDeprecations/DeprecatedWindowsVersionCheck check

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/log_resource_notifications.rb
spec/rubocop/cop/chef/deprecation/log_resource_notification_spec.rb

Add ChefDeprecations/LogResourceNotifications cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/resource_without_name_or_provides.rb
spec/rubocop/cop/chef/deprecation/resource_without_name_or_provides_spec.rb

Add ChefDeprecations/ResourceWithoutNameOrProvides cop

---

RELEASE_NOTES.md
WRITING_RULES.md
config/upstream.yml
lib/rubocop/monkey_patches/comment_config.rb
lib/rubocop/monkey_patches/config.rb

Add release notes for Cookstyle 6

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/conditional_ruby_shellout.rb
spec/rubocop/cop/chef/correctness/conditional_ruby_shellout_spec.rb

Turns out people are doing WAY too much work to just shellout.

Add ChefCorrectness/ConditionalRubyShellout cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/node_roles_include.rb
spec/rubocop/cop/chef/modernize/node_roles_include_spec.rb

Simplify how people check to see if a node includes a role

Add ChefModernize/NodeRolesInclude rule

---

config/cookstyle.yml
lib/rubocop/cop/chef/redundant/use_create_if_missing.rb
spec/rubocop/cop/chef/redundant/use_create_if_missing_spec.rb

This catches a subset of the total offenses, but it's a starting point.

Add ChefRedundantCode/UseCreateIfMissing cop

---

docs/cops_chefcorrectness.md
lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
spec/rubocop/cop/chef/correctness/incorrect_library_injection_spec.rb

Signed-off-by: Nathan Cerny <ncerny@chef.io>
Fixes syntax issue in ChefCorrectness/IncorrectLibraryInjection cop.
Fixes #597

Fix syntax on ChefCorrectness/IncorrectLibraryInjection.

---

config/cookstyle.yml
lib/rubocop/cop/chef/style/negating_only_if.rb
spec/rubocop/cop/chef/style/negating_only_if_spec.rb

Use a not_if instead
Fixes #513 

Detect code that negates an only_if

---

RELEASE_NOTES.md

Add Cookstyle 6.2 notes

---

lib/rubocop/cop/chef/style/negating_only_if.rb
spec/rubocop/cop/chef/style/negating_only_if_spec.rb

Make sure we don't alert on only_if statements in InSpec controls because there's no not_if there
Fix a crash that occurred and add some specs for that scenario

Fix a crash and false positive in ChefStyle/NegatingOnlyIf

---

.expeditor/config.yml
.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
config/cookstyle.yml
config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

This resolves a few important bugs that I've run into

Update to RuboCop 0.82 engine

---

RELEASE_NOTES.md

Add Cookstyle 6.3 notes

---

lib/rubocop/cop/chef/deprecation/deprecated_shellout_methods.rb
spec/rubocop/cop/chef/deprecation/deprecated_shellout_methods_spec.rb

Add a few missing shell_out methods

---

.expeditor/config.yml

Get a release out with fixes for the last DK 4

Wire up the 5-stable branch

---

.expeditor/config.yml
README.md
config/cookstyle.yml
docs/cops_chefcorrectness.md
lib/rubocop/cop/chef/correctness/dnf_package_allow_downgrades.rb
lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
lib/rubocop/cop/chef/deprecation/depends_partial_search.rb
lib/rubocop/cop/chef/deprecation/deprecated_yum_repository_properties.rb
lib/rubocop/cop/chef/deprecation/launchd_deprecated_hash_property.rb
lib/rubocop/cop/chef/deprecation/verify_property_file_expansion.rb
lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb
lib/rubocop/cop/chef/modernize/default_action_initializer.rb
lib/rubocop/cop/chef/modernize/powershell_install_windowsfeature.rb
lib/rubocop/cop/chef/modernize/respond_to_provides.rb
lib/rubocop/cop/chef/modernize/whyrun_supported_true.rb
lib/rubocop/cop/chef/redundant/sensitive_property_in_resource.rb
lib/rubocop/cop/chef/redundant/unnecessary_name_property.rb
spec/rubocop/cop/chef/correctness/dnf_package_allow_downgrades_spec.rb
spec/rubocop/cop/chef/correctness/incorrect_library_innjection_spec.rb
spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
spec/rubocop/cop/chef/modernize/powershell_install_windowsfeature_spec.rb
spec/rubocop/cop/chef/modernize/respond_to_provides_spec.rb
spec/rubocop/cop/chef/modernize/whyrun_supported_true_spec.rb
spec/rubocop/cop/chef/redundant/sensitive_property_in_resource_spec.rb
spec/rubocop/cop/chef/redundant/unnecessary_name_property_spec.rb

Fixup a few things for the last 5.x release that'll go into DK 4

Backport many fixes / autocorrection improvements from 6.x

---

RELEASE_NOTES.md

This also adds 5.22 release notes that have already been reviewed

Add 5.23 release notes

---

lib/rubocop/cop/target_chef_version.rb
tasks/cops_documentation.rake

This is pretty important information for running these cops

Document the target chef version of each cop

---

lib/rubocop/cop/chef/deprecation/depends_compat_resource.rb
lib/rubocop/cop/chef/deprecation/depends_partial_search.rb
lib/rubocop/cop/chef/deprecation/easy_install.rb
lib/rubocop/cop/chef/deprecation/erl_call.rb
lib/rubocop/cop/chef/deprecation/locale_lc_all_property.rb
lib/rubocop/cop/chef/deprecation/node_methods_not_attributes.rb
lib/rubocop/cop/chef/deprecation/node_set.rb
lib/rubocop/cop/chef/deprecation/node_set_unless.rb
lib/rubocop/cop/chef/deprecation/powershell_cookbook_helpers.rb
spec/rubocop/cop/chef/deprecation/easy_install_spec.rb
spec/rubocop/cop/chef/deprecation/erl_call_spec.rb
spec/rubocop/cop/chef/deprecation/locale_lc_all_property_spec.rb
spec/rubocop/cop/chef/deprecation/powershell_cookbook_helpers_spec.rb

Use marketing names and update versions

Update some descriptions

---

config/cookstyle.yml

These were not being honored because they were missing the leading /

Fix our files and vendor exclusion to work

---

RELEASE_NOTES.md

Add Cookstyle 6.4 release notes

---

RELEASE_NOTES.md

mistyped name

---

RELEASE_NOTES.md

Minor release note update about cop `ChefRedundantCode/UseCreateIfMissing` example:
```
file '/etc/some/config' do
content 'value = true'
only_if { ::File.exist?('/etc/some/config') }
end
```
with
```
file '/etc/some/config' do
content 'value = true'
not_if { ::File.exist?('/etc/some/config') }
end
```
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

Minor update RELEASE_NOTES.md#cookstyle-62

---

Gemfile
lib/rubocop/cop/chef/deprecation/xml_ruby_recipe.rb
spec/rubocop/cop/chef/deprecation/xml_ruby_recipe_spec.rb

Catch inline conditionals and nuke those as well.

Catch conditionals in ChefDeprecations/IncludingXMLRubyRecipe

---

RELEASE_NOTES.md
config/cookstyle.yml

Add Cookstyle 6.6 release notes

---

config/cookstyle.yml

Add more styleguide links

---

spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb
spec/rubocop/cop/chef/style/unnecessary_platform_case_statement_spec.rb

Better use the included helpers

Improve a few specs

---

RELEASE_NOTES.md

Add Cookstyle 6.8 release notes

---

lib/rubocop/cop/chef/correctness/invalid_version_metadata.rb
lib/rubocop/cop/chef/sharing/invalid_license_string.rb

A few autocorrected perf optimizations

Minor optimizations from Rubocop Performance

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Adds autocorrection to several cops and fixes a few bugs

Update Rubocop to 0.86

---

config/cookstyle.yml
lib/rubocop/cop/chef/redundant/multiple_platform_checks.rb
spec/rubocop/cop/chef/redundant/multiple_platform_checks_spec.rb

Convert multiple platform checks into 1

Add new ChefRedundantCode/MultiplePlatformChecks cop

---

RELEASE_NOTES.md

Add release notes for 6.10

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb
spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb

Update RuboCop engine to 0.87.1

---

RELEASE_NOTES.md

Add release notes for 6.11

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/ use_automatic_resource_name.rb
spec/rubocop/cop/chef/deprecation/use_automatic_resource_name_spec.rb

This method is removed in Chef Infra Client 16+

Add ChefDeprecations/UseAutomaticResourceName cop

---

RELEASE_NOTES.md

Add release notes for 6.12

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/cron_d_file_or_template.rb
spec/rubocop/cop/chef/modernize/cron_d_file_or_template_spec.rb

Add new ChefModernize/CronDFileOrTemplate cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/supports_must_be_float.rb
spec/rubocop/cop/chef/correctness/supports_must_be_float_spec.rb

Add ChefCorrectness/SupportsMustBeFloat

---

RELEASE_NOTES.md

Add release notes for 6.13

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/ruby_27_keyword_argument_warnings.rb
lib/rubocop/cop/chef/modernize/action_method_in_resource.rb
spec/rubocop/cop/chef/modernize/action_method_in_resource_spec.rb

Add ChefModernize/ActionMethodInResource cop

---

lib/rubocop/cop/chef/redundant/ohai_attribute_to_string.rb

Originally this was just a platform check.

Fix matcher name to match what we're doing

---

lib/rubocop/cop/chef/correctness/invalid_platform_family_helper.rb
spec/rubocop/cop/chef/correctness/invalid_platform_family_helper_spec.rb

Add autocorrection to ChefCorrectness/InvalidPlatformFamilyHelper

---

RELEASE_NOTES.md

Add 6.14 release notes

---

config/cookstyle.yml

Metrics cops are just annoying.

Disable Metrics/BlockNesting and Metrics/ParameterLists

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update to RuboCop 0.89

---

RELEASE_NOTES.md

Add 6.15 release notes

---

lib/rubocop/cop/chef/sharing/empty_metadata_field.rb
spec/rubocop/cop/chef/sharing/empty_metadata_field_spec.rb

Fix typo in ChefSharing/EmptyMetadataField

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop engine to 0.90

---

RELEASE_NOTES.md

Add release notes for Cookstyle 6.16

---

RELEASE_NOTES.md

Add Cookstyle 6.17 release notes

---

lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
spec/rubocop/cop/chef/correctness/incorrect_library_injection_spec.rb

This will catch far more offenses now.

ChefCorrectness/IncorrectLibraryInjection: Catch more offenses

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/lazy_in_resource_guard.rb
spec/rubocop/cop/chef/correctness/lazy_in_resource_guard_spec.rb

This detects bad guard code
Closes https://github.com/chef/cookstyle/issues/705

Add new ChefCorrectness/LazyInResourceGuard cop

---

config/cookstyle.yml

Help people remove some extra code to simplify their resources or libraries.

Enable Lint/RedundantRequireStatement cop

---

config/cookstyle.yml
lib/cookstyle.rb

These are useful built-in cops for simplifying Ruby.

Enable 8 more RuboCop cops to simplify code

---

RELEASE_NOTES.md

Cookstyle 6.18 release notes

---

lib/rubocop/cop/chef/modernize/respond_to_metadata.rb
spec/rubocop/cop/chef/modernize/respond_to_metadata_spec.rb

This is a weird one for old Berkshelf I assume.

Catch more legacy metadata gating

---

lib/rubocop/cop/chef/effortless/chef_vault_used.rb
lib/rubocop/cop/chef/effortless/depends_chef_vault.rb

Make these match the PR changes that were made to the docs.

Update the description for the new vault plugins

---

RELEASE_NOTES.md

Add release notes for 6.19

---

lib/rubocop/cop/chef/deprecation/deprecated_chefspec_platform.rb

Remove extra Gem::Dependency.new code

---

.expeditor/config.yml
DEVELOPER_GUIDE.md
README.md
RELEASE_NOTES.md
config/cookstyle.yml
cookstyle.gemspec

Migrate master branch to main

---

.gitignore
config/cookstyle.yml
config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update to RuboCop 0.93

---

README.md

The previous commits to master are not in the changelog

Update copyright to bump version

---

RELEASE_NOTES.md

Add release notes for 6.20

---

config/upstream.yml
lib/cookstyle/version.rb

This includes an important bugfix for begin/end

Update RuboCop to 0.93.1

---

RELEASE_NOTES.md

Add release notes for 6.21

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/librarian_chefspec.rb
spec/rubocop/cop/chef/deprecation/librarian_chefspec_spec.rb

Add a new Chef/Deprecations/LibrarianChefSpec cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/foodcritic_testing.rb
spec/rubocop/cop/chef/deprecation/foodcritic_testing_spec.rb

Add new Chef/Deprecations/FoodcriticTesting cop

---

RELEASE_NOTES.md

Cookstyle 7.0 release notes

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update to RuboCop 1.2.0

---

RELEASE_NOTES.md

Add release notes for Cookstyle 7.1

---

Gemfile
Rakefile

I think this came in during testing of cops

Remove extra dev deps

---

Gemfile
config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop to 1.3.0

---

config/upstream.yml
lib/cookstyle/version.rb
spec/spec_helper.rb

Update RuboCop to 1.3.1

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Bump RuboCop to 1.4.1

---

config/cookstyle.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop to 1.4.2

---

config/cookstyle.yml

Don't use DSL actions in HWRPs

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/deprecated_yum_repository_actions.rb
spec/rubocop/cop/chef/deprecation/deprecated_yum_repository_actions_spec.rb

There's an alias for these methods in the chef/chef codebase right now, but we should really get everyone on the consistent actions.

Add new Chef/Deprecations/DeprecatedYumRepositoryActions cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/chef_sugar_helpers.rb
spec/rubocop/cop/chef/deprecation/chef_sugar_helpers_spec.rb

This helps identify code still using chef-sugar.

Add new Chef/Deprecations/ChefSugarHelpers cop

---

config/cookstyle.yml
config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update to RuboCop 1.5.0

---

RELEASE_NOTES.md

Add release notes for 7.3

---

.expeditor/run_linux_tests.sh
Gemfile
Rakefile
lib/cookstyle/version.rb

Update RuboCop to 1.5.2

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop to 1.7.0

---

RELEASE_NOTES.md

Add release notes for 7.6

---

lib/rubocop/cop/chef/sharing/invalid_license_string.rb

Update the list of SPDX license strings

---

config/upstream.yml
lib/cookstyle/version.rb

This includes my fix for how the styleguide docs URLs are generated.

Update RuboCop to 1.9.1

---

config/cookstyle.yml

Enable Lint/ErbNewArguments cop

---

tasks/cops_documentation.rake

Trim out the current directory from the include/exclude arrays
Split out name into short_name and full_name

Improve the yaml we generate

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Bump RuboCop to 1.10

---

.expeditor/build_docs.sh

Stop generating the legacy markdown docs

---

README.md

Update link to the docs in the readme

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Bug fixes and autocorrect improvements

Update RuboCop engine to 1.11

---

lib/rubocop/cop/chef/correctness/block_guard_clause_string_only.rb
lib/rubocop/cop/chef/correctness/chef_application_fatal.rb
lib/rubocop/cop/chef/correctness/conditional_ruby_shellout.rb
lib/rubocop/cop/chef/correctness/dnf_package_allow_downgrades.rb
lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
lib/rubocop/cop/chef/correctness/invalid_notification_timing.rb
lib/rubocop/cop/chef/correctness/invalid_platform_family_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_family_values_in_case.rb
lib/rubocop/cop/chef/correctness/invalid_platform_helper.rb
lib/rubocop/cop/chef/correctness/invalid_platform_metadata.rb
lib/rubocop/cop/chef/correctness/invalid_platform_values_in_case.rb
lib/rubocop/cop/chef/correctness/invalid_value_for_platform_family_helper.rb
lib/rubocop/cop/chef/correctness/invalid_value_for_platform_helper.rb

Improve resource docs

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle.rb
lib/cookstyle/version.rb
lib/rubocop/monkey_patches/directive_comment.rb
spec/rubocop/monkey_patches/cookstyle_comment_spec.rb

Update to the latest RuboCop with a bunch of detection improvements

Update RuboCop to 1.12

---

lib/cookstyle/version.rb

Update to RuboCop 1.12.1

---

.expeditor/verify.pipeline.yml
config/cookstyle.yml
config/disable_all.yml
config/upstream.yml
cookstyle.gemspec
lib/cookstyle/version.rb
tasks/cops_documentation.rake

Update to RuboCop 1.13 and parse Ruby 2.5 and later only

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop Engine to 1.14

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/hwrp_without_unified_mode_true.rb
spec/rubocop/cop/chef/deprecation/hwrp_without_unified_mode_true_spec.rb

No autocorrection yet, but it will detect HWRPs missing unified_mode

Add new unified_mode cop for HWRPs

---

.expeditor/verify.pipeline.yml

Test on Ruby 3.0

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/metadata_missing_name.rb
lib/rubocop/cop/chef/deprecation/resource_without_unified_mode_true.rb
spec/rubocop/cop/chef/deprecation/resource_without_unified_mode_true_spec.rb

No autocorrect here, but that's next

Add new cop for unified mode in custom resources

---

lib/rubocop/cop/chef/modernize/windows_registry_uac.rb
spec/rubocop/cop/chef/modernize/windows_registry_uac_spec.rb

Just because you're mucking with the same key doesn't mean you're
setting values supported by windows_uac

Fix false positive in WindowsRegistryUAC

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update to RuboCop 1.15

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop to 1.17

---

tasks/cops_documentation.rake

Make sure we generate documentation for InSpec cops

---

RELEASE_NOTES.md

Add Cookstyle 7.14 release notes

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop engine to 1.18.3

---

lib/cookstyle/version.rb

Update to RuboCop 1.18.4

---

.github/ISSUE_TEMPLATE/NEW_COP_REQUEST.md

Adds InSpec/Deprecations to the issue template so that users can request new cops for InSpec.
Adds new lines under headings.

Adds InSpec/Deprecations to the issue template

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/metadata_malformed_version.rb
spec/rubocop/cop/chef/correctness/metadata_malformed_depends_spec.rb

Catch these before they error in the client

Add a new cop for detecting malformed cookbook depends

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Update RuboCop to 1.19

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/deprecated_sudo_actions.rb
spec/rubocop/cop/chef/deprecation/deprecated_sudo_actions_spec.rb

Catch these legacy action names

Add a new cop Chef/Deprecations/DeprecatedSudoActions

---

lib/rubocop/cop/chef/style/immediate_notification_timing.rb
spec/rubocop/cop/chef/style/immediate_notification_timing_spec.rb

These should get updated as well

Updates Chef/Style/ImmediateNotificationTiming to support subscribes

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/metadata_malformed_version.rb
lib/rubocop/cop/chef/deprecation/depends_omnibus_updater_cookbook.rb
lib/rubocop/cop/chef/modernize/depends_openssl_cookbook.rb
spec/rubocop/cop/chef/deprecation/depends_omnibus_updater_cookbook_spec.rb
spec/rubocop/cop/chef/modernize/depends_openssl_cookbook_spec.rb

Fix typos in the docs + incorrect description in config

---

.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
config/cookstyle.yml
lib/rubocop/cop/chef/modernize/use_chef_language_env_helpers.rb
spec/rubocop/cop/chef/modernize/use_chef_language_env_helpers_spec.rb

Simplify detecting if we're in CI or not.

Add new Chef/Modernize/UseChefLanguageEnvHelpers cop

---

.expeditor/build_docs.sh
.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
Gemfile

Signed-off-by: Swati Keshari <skeshari@msystechnologies.com>

Replace deprecated --without flag with bundle config

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/class_eval_action_class.rb
spec/rubocop/cop/chef/modernize/class_eval_action_class_spec.rb

Add Chef/Modernize/ClassEvalActionClass cop

---

lib/rubocop/cop/chef/deprecation/resource_without_unified_mode_true.rb

Fix typo in description

---

config/cookstyle.yml
lib/rubocop/cop/chef/modernize/use_chef_language_systemd_helper.rb
spec/rubocop/cop/chef/modernize/use_chef_language_systemd_helper_spec.rb

Add Chef/Modernize/UseChefLanguageSystemdHelper cop

---

config/cookstyle.yml
lib/rubocop/cop/chef/correctness/metadata_missing_version.rb
spec/rubocop/cop/chef/correctness/metadata_missing_version.rb

This allows us to implement https://github.com/chef/supermarket/issues/2183

Add Chef/Correctness/MetadataMissingVersion

---

config/disable_all.yml
config/upstream.yml

Obvious fix; these changes are the result of automation not creative thinking.

Vendor rubocop-1.21.0 upstream configuration.

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb
spec/rubocop/cop/chef/correctness/invalid_platform_family_helper_spec.rb
spec/rubocop/cop/chef/correctness/macos_userdefaults_invalid_type_spec.rb
spec/rubocop/cop/chef/correctness/node_normal_spec.rb
spec/rubocop/cop/chef/correctness/node_normal_unless_spec.rb
spec/rubocop/cop/chef/deprecation/deprecated_chefspec_platform_spec.rb
spec/rubocop/cop/chef/style/unnecessary_platform_case_statement_spec.rb

Obvious fix; these changes are the result of automation not creative thinking.

Update RuboCop to 1.22

---

config/cookstyle.yml

These should get updated to https

Flag http rubygems sources in gemfiles

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb

Lots of bug fixes and improvements

Update RuboCop to 1.23

---

config/disable_all.yml
config/upstream.yml
lib/cookstyle/version.rb
lib/rubocop/monkey_patches/directive_comment.rb

Update RuboCop to 1.24.1

---

Rakefile
config/cookstyle.yml
tasks/cops_documentation.rake

This greatly simplifies some library code and makes it easier for the next person to maintain

Enable cops to simplify file read/writes

---

config/cookstyle.yml
lib/rubocop/cop/chef/security/ssh_private_key.rb
spec/rubocop/cop/chef/security/ssh_private_key_spec.rb

Add our first cop to detect security problems in cookbook code.

Add new Chef/Security department and Chef/Security/SshPrivateKey cop

---

.github/ISSUE_TEMPLATE/NEW_COP_REQUEST.md
lib/rubocop/cop/chef/security/ssh_private_key.rb

Minor updates for the security cops

---

.github/workflows/unit.yml

Test on Ruby 3.1

---

lib/rubocop/cop/chef/deprecation/depends_poise.rb
spec/rubocop/cop/chef/deprecation/depends_poise_spec.rb

Detect usage of deprecated poise-hoist

---

config/upstream.yml
lib/cookstyle/version.rb

This includes a large number of bug fixes

Update RuboCop engine to 1.25

---

config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/delivery.rb

Add a new Chef/Deprecations/Delivery cop

---

lib/rubocop/cop/chef/correctness/metadata_missing_name.rb
lib/rubocop/cop/chef/correctness/metadata_missing_version.rb

Handle metadata.rb file being empty

---

config/cookstyle.yml

Fix the config to enable Chef/Security/SshPrivateKey

---

.rubocop.yml
config/cookstyle.yml
lib/rubocop/cop/chef/deprecation/foodcritic_file.rb
lib/rubocop/cop/chef/deprecation/use_automatic_resource_name.rb
spec/rubocop/cop/chef/deprecation/foodcritic_file_spec.rb

Detect legacy .foodcritic files

Add Chef/Deprecations/FoodcriticFile cop

---

config/cookstyle.yml

Signed-off-by: Doug Knight <doug.knight@karmix.org>
Some configurations for cops will cause them to raise offenses when run against a TOML or JSON file that also happens to be syntactically valid Ruby.  When customers customize cop configurations, the cops may make recommendations or perform auto-corrections that are not valid in TOML or JSON.  This patch excludes these files from consideration by the cops in the `Layout`, `Lint`, `Style`, and `Chef/Style` departments to reduce the likelihood of this happening.
Addresses issue with PR #951 which fixed #942

Don't autocorrect Delivery's TOML or JSON files

---

.github/CODEOWNERS

Requiring docs team approval for this project seems a bit heavy-handed for a linter. Removing.

Remove docs team as required for md here

---

config/cookstyle.yml

Correct styleguide link for TmpPath

---

.expeditor/habitat-test.pipeline.yml

Testing publish pipeline

---

.expeditor/config.yml

Added the release branch

---

.expeditor/config.yml
lib/cookstyle/version.rb

Adding back the pipelines and added agents workload to promote

Adding back the pipelines

---

.expeditor/config.yml

Remove pipeline config to build automated pipeline

Remove pipeline config to build automated pipeline

---

.expeditor/config.yml

Added pipeline config to build automatically

Added pipeline config to build automatically

---

RELEASE_NOTES.md
lib/cookstyle/version.rb

Update RuboCop to 1.75.5

---

RELEASE_NOTES.md
lib/cookstyle/version.rb
lib/rubocop/cop/chef/deprecation/delivery.rb

Bug fixes: https://github.com/rubocop/rubocop/releases/tag/v1.75.6

Update RuboCop to 1.75.6

---

CODE_OF_CONDUCT.md
RELEASE_NOTES.md
WRITING_RULES.md
config/chefstyle.yml
config/cookstyle.yml
lib/cookstyle/version.rb
lib/rubocop/cop/chef/modernize/libarchive_file.rb

More bug fixes
https://github.com/rubocop/rubocop/releases/tag/v1.75.7

Update RuboCop to 1.75.7

---

RELEASE_NOTES.md
config/chefstyle.yml
config/cookstyle.yml
lib/cookstyle/version.rb

Enable a few new cops from this

Update to RuboCop 1.76.1

---

lib/cookstyle/version.rb

Lots of improvements and bug fixes
None

Update RuboCop to 1.79.1

---

RELEASE_NOTES.md
lib/cookstyle/version.rb
lib/rubocop/cop/chef/correctness/empty_resource_guard.rb

Pull in minor bug fixes and prep an 8.4 release

Update RuboCop to 1.79.2 + prep release
