- config/cookstyle.yml
this was the setting that even made vargo admit that rubocop was jumping the shark in favor of trying to construct their own flavor of the ruby language with their own finely honed ground down axes that nobody in their right mind really wanted.
this favors cut+paste over the bizzare 'its like the english language' argument that rubocop's authors use to defend the default behavior.
everyone hates editing raw JSON files because it enforces semicolon usage the way rubocop's default does.
rubocop is currently enforcing this:
```ruby
[
"foo",
"bar"
]
```
this change will start to enforce this:
```ruby
[
"foo",
"bar",
]
```
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
> set TrailingCommaInLiteral correctly

- config/cookstyle.yml
Underscores in numbers are unnecessary, especially for port numbers in attributes where they are unexpected (ie. 1_234)
Signed-off-by: Matt Ray <matthewhray@gmail.com>
> Underscores in numbers are unnecessary

- config/cookstyle.yml
fires for too many trivial cases.
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>
> disable CyclomaticComplexity

- config/cookstyle.yml
This is a handy cop, but it doesn’t autocorrect yet
> Disable Bundler/OrderedGems until there’s an autocorrect

- config/cookstyle.yml
I mean to disable Style/TernaryParentheses per Lamont's feedback
Lint/ShadowedException was meant to be enabled
> Fixup two mistakes in the 1.0 config

- config/cookstyle.yml
- config/cookstyle_base.yml
We should disable Metrics/ClassLength as well. Also avoid turning off things we just turned on in the base rubocop.yml
> Disable Metrics/ClassLength and cleanup cookstyle_base

- .travis.yml
- CHANGELOG.md
- config/cookstyle.yml
- lib/cookstyle/version.rb
Slip 1 more change in and release 1.4.0. After this I'll bump Rubocop and release 2.0
> Disable Performance/Casecmp and release 1.4.0

- CHANGELOG.md
- config/cookstyle.yml
- config/cookstyle_base.yml
- lib/cookstyle/version.rb
> Enforce LF for line endings to prevent failures on windows

- config/cookstyle.yml
Giving this another shot since #37 was a bit too early and with ChefDK 3.0 on the horizon it seems fitting to target a newer Ruby.
> Change target Ruby to at least 2.3

- config/cookstyle.yml
Looking for feedback on what rules here people are heavy objections to. I skipped over quite a few that had no impact on cookbooks (gemspec stuff) and some that were just WAY to opinionated (class formatting stuff).
> Enable new rules between 0.49 -> 0.55

- config/cookstyle.yml
Since lazy is a decorator method a yield of the block isn't always implicit and thus can break more often than work. Closes #52
> Ignore lazy { } for symbol proc check

- cookstyle.gemspec
This breaks installs on systems with bundler 2.x
> Unpin the bundler dev dep

- .expeditor/update_version.sh
Other projects have double quotes, but cookstyle is linted with
cookstyle (which is kinda odd btw).
> Fix the update version script for expeditor

- config/cookstyle.yml
- lib/cookstyle.rb
- lib/rubocop/cop/chef/node_set.rb
autocorrects to node.normal.
we need a Chef/NodeNormal to warn about that, but this is a tiny bit
of progress.
> add Chef/NodeSet cop with autocorrect

- .expeditor/config.yml
- .expeditor/update_version.sh
- .github/CODEOWNERS
- lib/cookstyle/version.rb
Fix quoting in our version bump script by just using our standard sed command and double quotes in the cookstyle version file.
> Fix version bumps and codeowners

- config/cookstyle.yml
These are used by cookstyle --show-cops so it's important to get them right.
> Add and update cookstyle cop descriptions

- config/cookstyle.yml
- lib/rubocop/cop/chef/insecure_cookbook_url.rb
These represent almost all of the community cookbook and this makes sure folks are using secure URLs
> Add an autocorrect for insecure gitlab/github source/issue url metadata

- config/cookstyle.yml
- lib/rubocop/cop/chef/comment_sentence_spacing.rb
This is a new cop that correct sentences in comment blocks to only have a single space after the period.
> Add Chef/CommentSentenceSpacing cop (disabled by default)

- lib/rubocop/cop/chef/comment_sentence_spacing.rb
Support sentences that end in a question mark
Don't match on more than 2 spaces because there may be a reason for that (who knows :shrug:)
> Improve detection of double spaces after sentences

- bin/cookstyle
- lib/rubocop/cop/chef/attribute_keys.rb
- lib/rubocop/cop/chef/berksfile_source.rb
- lib/rubocop/cop/chef/comment_sentence_spacing.rb
- lib/rubocop/cop/chef/comments_copyright_format.rb
- lib/rubocop/cop/chef/comments_format.rb
- lib/rubocop/cop/chef/file_mode.rb
- lib/rubocop/cop/chef/insecure_cookbook_url.rb
- lib/rubocop/cop/chef/node_normal.rb
- lib/rubocop/cop/chef/node_normal_unless.rb
- lib/rubocop/cop/chef/node_set.rb
- lib/rubocop/cop/chef/node_set_unless.rb
- lib/rubocop/cop/chef/service_resource.rb
- lib/rubocop/cop/chef/tmp_path.rb
This way we can introduce new rules without failing builds. They'll warn to the console and auto correct, but they won't fail CI
> Force the fail level to :convention and set rules to :refactor level

- config/cookstyle.yml
- lib/rubocop/cop/chef/property_with_name_attribute.rb
This catches properties that define a name_attribute instead of a name_property
> Add new PropertyWithNameAttribute rule

- config/cookstyle.yml
- lib/rubocop/cop/chef/property_with_default_and_required.rb
Detect properties that are required but have a default that will never be used.
This doesn't have an autocorrect yet since it really should be done in the ast to be correct spacing wise.
> Add new Chef/PropertyWithRequiredAndDefault

- .expeditor/verify.pipeline.yml
- lib/rubocop/cop/chef/comments_format.rb
Don't process past line 10 because we're not in a header anymore and a sentence might start with one of our keywords.
> Avoid false positives in header cleanup

- config/cookstyle.yml
- lib/rubocop/cop/chef/data_bags.rb
- lib/rubocop/cop/chef/search.rb
Detect if a cookbook uses data bags or search. Disabled by default.
> Add rules for Effortless Infra pattern

- .expeditor/verify.pipeline.yml
- Gemfile
- Rakefile
- spec/expect_violation/expectation_spec.rb
- spec/rubocop/cop/chef/attribute_keys_spec.rb
- spec/rubocop/cop/chef/file_mode_spec.rb
- spec/rubocop/cop/chef/service_resource_spec.rb
- spec/rubocop/cop/chef/tmp_path_spec.rb
- spec/shared/autocorrect_behavior.rb
- spec/shared/detects_style_behavior.rb
- spec/shared/rspec_only_cop_behavior.rb
- spec/spec_helper.rb
- spec/support/expect_violation.rb
This does not add the cookbook_only specs which are all failing right now. That may just be because that functionality is broken. We're not actually using it anywhere.
> Add the majority of specs from rubocop-chef

- config/cookstyle.yml
Chef/UseBuildEssentialResource will update cookbooks to require Chef Infra 14+ or later. Let's hold off on this until we have a better way to specify the Chef Infra version users are running.
> Add introduced fields and turn off Chef/UseBuildEssentialResource by default

- config/cookstyle.yml
- lib/rubocop/cop/chef/poise.rb
- spec/rubocop/cop/chef/poise_spec.rb
This detects a cookbook that depends on the poise cookbook, which is no longer being maintained. These should be refactored to use custom resources instead.
Fixes #135 
> Add Chef/CookbookDependsOnPoise rule

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/require_recipe.rb
- spec/rubocop/cop/chef/deprecation/require_recipe_spec.rb
Detect when someone does this:
```ruby
require_recipe 'foo'
```
instead of
```ruby
include_recipe 'foo'
```
> Add Chef/RequireRecipe rule

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/long_description_metadata.rb
- spec/rubocop/cop/chef/deprecation/long_description_metadata_spec.rb
There's no need for long_description at this point and it just makes the metadata more complex and Chef just a tiny bit harder to use.
> Add Chef/LongDescriptionMetadata cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/respond_to_metadata.rb
- lib/rubocop/cop/chef/modernize/build_essential.rb
- spec/rubocop/cop/chef/deprecation/respond_to_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/build_essential_spec.rb
Make sure to be clear about what new versions mean for users in terms of compatibility with Chef Infra Client releases.
> Enable UseBuildEssentialResource and improve messaging

- config/cookstyle.yml
*.rb per the Rubocop docs not *.\.rb, which doesn't actually match
> Fix file matching in the configs

- lib/rubocop/cop/chef/deprecation/respond_to_metadata.rb
The typo is in both locations so this doesn't impact the operation of the cop, but we should fix it.
> Fix typo in method name

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/respond_to_provides.rb
- lib/rubocop/cop/chef/modernize/respond_to_resource_name.rb
- spec/rubocop/cop/chef/modernize/respond_to_provides_spec.rb
- spec/rubocop/cop/chef/modernize/respond_to_resource_name_spec.rb
Catch some old school gating that's floating around.
> Add Chef/RespondToResourceName and Chef/RespondToProvides cops

- .gitignore
- lib/rubocop/cop/chef/correctness/cb_depends_on_self.rb
- spec/rubocop/cop/chef/correctness/cb_depends_on_self_spec.rb
If we change the node to the depends node we found then we can delete it easily.
> Add autocorrecting to CookbooksDependsOnSelf

- bin/cookstyle
We started injecting the fail-level by default which meant we went from 1 arg to 3.
```shell
≻ bin/cookstyle -v
Cookstyle 5.2.11
* RuboCop 0.72.0
```
> Fix the regression where we no longer show the cookstyle version

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/block_guard_clause_string_only.rb
- spec/rubocop/cop/chef/correctness/block_guard_clause_string_only_spec.rb
This detects incorrectly setup guards that will always return true. There are currently three of these on the Supermarket even though we had a foodcritic rule for this.
> Add Chef/BlockGuardWithOnlyString

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/resource_with_allowed_action.rb
- spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
Detect when a custom resource uses allowed_actions, which is no longer necessary.
> Add Chef/CustomResourceWithAllowedActions

- lib/rubocop/cop/chef/correctness/invalid_license_string.rb
A ran into this one as well. Seems like that might be common.
> Autocorrect Apache v2.0 license to Apache-2.0

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/execute_apt_update.rb
- spec/rubocop/cop/chef/modernize/execute_apt_update_spec.rb
Detect when someone is using execute to run apt-get update. This catches
the most basic offense of this. Once I have more advanced resource
inspection I'll catch commands in an execute that has a friendly
resource name.
> Add Chef/ExecuteAptUpdate rule

- lib/rubocop/cop/chef/style/comments_format.rb
Our regex would only work with a single space. This corrects that.
> Fix autocorrection of comments that are indented with more than one space

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/node_methods_not_attributes.rb
- spec/rubocop/cop/chef/deprecation/node_methods_not_attributes_spec.rb
This detects changes due our the removal of the node method missing behavior in Chef 13. I'm not calling it that because no one knows what method missing is who just needs to clean up some cookbooks. This catches the bad methods we can be 100% sure of. There's 250 of these on the supermarket. Obviously it's not going to catch all your cookbook attributes, but it gets you a bit closer.
> Add Chef/NodeMethodsInsteadofAttributes cop

- config/cookstyle.yml
Let's not bother checking the node matchers in metadata.rb for cops that won't ever match there.
> Avoid scanning metadata.rb files for rules that don't apply there

- config/cookstyle.yml
- lib/rubocop/cop/chef/effortless/node_save.rb
- lib/rubocop/cop/chef/modernize/whyrun_supported_true.rb
- spec/rubocop/cop/chef/modernize/whyrun_supported_true_spec.rb
- test.rb
:facepalm: I got the wrong method here.
> Fix Chef/WhyRunSupportedTrue to find the correct method

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/use_inline_resources.rb
- spec/rubocop/cop/chef/modernize/use_inline_resources_spec.rb
It's a bit funky because of if defined?(use_inline_resources) which screws things up and may double alert if we don't make sure to properly flag the right part of the ast.
> Add UseInlineResourcesDefined cop

- config/cookstyle.yml
This will only work when you're in the root of a cookbook, but that's
the safe way to do it.
Fixes #247 
> Exclude the files directory for scans

- RELEASE_NOTES.md
- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/includes_mixin_shellout.rb
- spec/rubocop/cop/chef/modernize/apt_default_recipe_spec.rb
- spec/rubocop/cop/chef/modernize/build_essential_spec.rb
- spec/rubocop/cop/chef/modernize/execute_apt_update_spec.rb
- spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb
- spec/rubocop/cop/chef/modernize/windows_default_recipe_spec.rb
- spec/rubocop/cop/chef/modernize/windows_version_helper_spec.rb
- spec/rubocop/cop/chef/modernize/windows_zipfile_spec.rb
Detect when someone is requiring / including the shellout mixin within a custom resource or LWRP. You don't need to do that.
> Add Chef/IncludingMixinShelloutInResources cop

- Rakefile
- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/node_save.rb
Add a rake task to check that all cops are in the config file. This will run in Buildkite and keep me from missing cops in the config. This also moves and enables Chef/CookbookUsesNodeSave which snuck in but was missing in the config.
> Validate that all cops are in the config in CI + add missing Chef/CookbookUsesNodeSave

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/libarchive_file.rb
- lib/rubocop/cop/chef/modernize/seven_zip_archive.rb
- spec/rubocop/cop/chef/modernize/libarchive_file_spec.rb
- spec/rubocop/cop/chef/modernize/seven_zip_archive_spec.rb
Get people using the built in archive_file resource instead of external dependencies.
> Add Chef/LibarchiveFile and Chef/SevenZipArchiveResource

- lib/rubocop/cop/chef/correctness/default_maintainer_metadata.rb
- lib/rubocop/cop/chef/deprecation/deprecated_mixins.rb
- spec/rubocop/cop/chef/correctness/default_maintainer_metadata_spec.rb
This is the format we use in the generator now
> Catch additional formats for default maintainer information in metadata

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb
- spec/rubocop/cop/chef/deprecation/windows_task_change_action_spec.rb
Catch the use of the old :change action. The cleanup in the autocorrect is a bit funky because we have to handle these two scenarios
action :change -> action :create
action [:create, :change] -> action :create
> Add ChefDeprecations/WindowsTaskChangeAction

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/recipe_metadata.rb
- spec/rubocop/cop/chef/deprecation/recipe_metadata_spec.rb
Detect recipe metadata and remove it. Metadata.rb is for machines and they don't use this data. Document this stuff in the readme.md instead.
> Add ChefDeprecations/RecipeMetadata cop

- lib/rubocop/cop/chef/style/use_platform_helpers.rb
This is a major facepalm here and looking back it makes total sense. All the on_* hooks run and then all the autocorrects run. That means when I set @type and @plat they'd get used by all the autocorrectors and every node['platform'
] == 'foo' would be autocorrected to the last platform found in the recipe.
resolves #301
> Fix autocorrection of multiple platform helpers in a recipe

- lib/rubocop/cop/chef/deprecation/long_description_metadata.rb
- spec/rubocop/cop/chef/deprecation/long_description_metadata_spec.rb
Avoid replacing a bogus metadata entry with a bogus empty line
> Remove the newline when autocorrecting long_description in metadata

- docs/cops_chefmodernize.md
- lib/rubocop/cop/chef/modernize/resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
As lamont pointed out the improvements in 12.5 that we call custom resources also apply to existing LWRPs. Previously this cop was gated to only run on custom resources, but that's not actually necessary. This speeds it up and catches more stuff.
> Update CustomResourceWithAllowedActions to trigger on LWRPs as well

- lib/rubocop/cop/chef/deprecation/use_inline_resources.rb
- spec/rubocop/cop/chef/deprecation/use_inline_resources_spec.rb
This is far less common than use_inline_resources if
defined?(use_inline_resources), but there's a few of them on the
supermarket and without this we break that code.
Resolves #297 
> Catch use_inline_resources if respond_to?(:use_inline_resources)

- lib/rubocop/cop/chef/deprecation/user_supports_property.rb
- spec/rubocop/cop/chef/deprecation/user_supports_property_spec.rb
Break out the items in the has into their own properties
> Add autocorrection to ChefDeprecations/UserDeprecatedSupportsProperty

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/unnecessary_name_property.rb
- spec/rubocop/cop/chef/correctness/unnecessary_name_property_spec.rb
There's a lot of these and they're not needed.
>  Add ChefCorrectness/UnnecessaryNameProperty

- config/cookstyle.yml
- docs/cops.md
- docs/cops_chefdeprecations.md
- lib/rubocop/cop/chef/deprecation/chefspec_coverage_report.rb
- lib/rubocop/cop/chef/deprecation/chefspec_legacy_runner.rb
- spec/rubocop/cop/chef/deprecation/chefspec_coverage_report_spec.rb
- spec/rubocop/cop/chef/deprecation/chefspec_legacy_runner_spec.rb
Detect usage of the deprecated ChefSpec coverage reporter and the usage of pre-ChefSpec 4.1 (2014) spec runners.
Resolves #302 
> Add ChefDeprecations/ChefSpecCoverageReport & ChefDeprecations/ChefSpecLegacyRunner cops

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/simplify_platform_major_version_check.rb
- spec/rubocop/cop/chef/style/simplify_platform_major_version_check_spec.rb
When checking the major version number of a platform you can take the node['platform_version'] attribute and transform it to an integer to strip it down to just the major version number. This simple way of determining the major version number of a platform should be used instead of splitting the platform into multiple fields with '.' as the delimiter.
node['platform_version'].split('.').first
node['platform_version'].split('.')[0]
node['platform_version'].split('.').first.to_i
node['platform_version'].split('.')[0].to_i
if node['platform_version'].to_i == 7
> Add ChefStyle/SimplifyPlatformMajorVersionCheck

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/invalid_version_metadata.rb
- spec/rubocop/cop/chef/correctness/invalid_version_metadata_spec.rb
This is from Foodcritic and is just as valid today as it was in 2013.
> Add ChefCorrectness/InvalidVersionMetadata cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/run_command_helper.rb
- spec/rubocop/cop/chef/deprecation/run_command_helper_spec.rb
Use 'shell_out!' instead of the legacy 'run_command' helper for shelling out. The run_command helper was removed in Chef Infra Client 13.
> Add ChefDeprecations/UsesRunCommandHelper cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/powershell_guard_interpreter.rb
- spec/rubocop/cop/chef/modernize/powershell_guard_interpreter_spec.rb
PowerShell is already set as the default guard interpreter for powershell_script resources in Chef Infra Client 13 and later and does not need to be specified.
> Add ChefModernize/PowerShellGuardInterpreter cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/chef_handler_supports.rb
- spec/rubocop/cop/chef/deprecation/chef_handler_supports_spec.rb
This allows cookbooks to run on Chef Infra Client 14 and later
> Add ChefDeprecations/ChefHandlerUsesSupports

- config/cookstyle.yml
- docs/cops_chef.md
- docs/cops_chefmodernize.md
- lib/rubocop/cop/chef/modernize/chef_14_resources.rb
- spec/rubocop/cop/chef/modernize/chef_14_resources_spec.rb
Update the node match to match any AST nodes after the method which will include any version constraint. I also improved the warning and docs for this cop.
> Fix ChefModernize/UnnecessaryDependsChef14 to detect version constraints

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/notifies_action_not_symbol.rb
- spec/rubocop/cop/chef/correctness/notifies_action_not_symbol_spec.rb
This prevents double notifications in Chef < 14 and it's just the correct way to write it.
> Add ChefCorrectness/NotifiesActionNotSymbol cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
We should also clean up allowed_actions in initializers when we find them. This will help folks to trim down the size of their HWRPs and more easily migrate them to DSL based custom resources.
> Expand ChefModernize/CustomResourceWithAllowedActions to work in HWRPs

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/node_normal.rb
- lib/rubocop/cop/chef/correctness/node_normal_unless.rb
- lib/rubocop/cop/chef/deprecation/eol_audit_mode.rb
- lib/rubocop/cop/chef/deprecation/node_set.rb
- lib/rubocop/cop/chef/deprecation/node_set_unless.rb
- spec/rubocop/cop/chef/correctness/node_normal_spec.rb
- spec/rubocop/cop/chef/deprecation/eol_audit_mode_spec.rb
- spec/rubocop/cop/chef/deprecation/node_set_spec.rb
- spec/rubocop/cop/chef/deprecation/node_set_unless_spec.rb
Detect the legacy audit mode and suggest folks check out InSpec
instead. This also cleans up some bad copyright dates.
33 occurrences of this were detected on Supermarket
> Add ChefDeprecations/EOLAuditModeUsage

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/inherits_compat_resource.rb
- spec/rubocop/cop/chef/deprecation/inherits_compat_resource_spec.rb
Detect resources coded against compat_resource since we deprecated that cookbook in the Chef 13 era.
> Add ChefDeprecations/ResourceInheritsFromCompatResource

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/verify_property_file_expansion.rb
- spec/rubocop/cop/chef/deprecation/verify_property_file_expansion_spec.rb
Detects incorrect verify property usage that breaks Chef 13+
> Add ChefDeprecations/VerifyPropertyUsesFileExpansion cop

- lib/rubocop/cop/chef/modernize/resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
This lets us catch this
```ruby
def initialize(*args)
super
@allowed_actions.push(:create, :remove)
end
```
> Expand what we detect in ChefModernize/CustomResourceWithAllowedActions

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- lib/rubocop/cop/chef/modernize/resource_name_initializer.rb
- spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
- spec/rubocop/cop/chef/modernize/resource_name_initializer_spec.rb
Migrating HWRPs into custom resources one DSL call at a time
> Add ChefModernize/DefaultActionFromInitialize and ChefModernize/ResourceNameFromInitialize:

- lib/rubocop/cop/chef/deprecation/depends_poise.rb
- spec/rubocop/cop/chef/deprecation/depends_poise_spec.rb
poise-service is the real one that folks need to migrate off of so we
should detect that as well.
> Detect poise-service in addition to just poise

- config/cookstyle.yml
These were not targeting the right files which meant they weren't really
running
> Fix the files we target with NotifiesActionNotSymbol & IncorrectLibraryInjection

- lib/rubocop/chef/cookbook_helpers.rb
- spec/rubocop/chef/cookbook_helpers_spec.rb
resource_block_name_if_string returns the name of the resource block if it's a string or nil if it's a variable and we can't parse it
match_resource_type? yields the node object if it finds a resource that matches the name passed
> Add additional helpers for working with resources

- config/cookstyle.yml
- config/disable_all.yml
- config/upstream.yml
- lib/cookstyle/version.rb
- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- lib/rubocop/cop/chef/modernize/resource_name_initializer.rb
- tasks/cops_documentation.rake
This resolves a large number of warnings and gives us a new cop for
automatically migrating the namespace of the cop disables in comments
* [#7407](https://github.com/rubocop-hq/rubocop/issues/7407): Make `Style/FormatStringToken` work inside hashes. ([@buehmann][])
* [#7389](https://github.com/rubocop-hq/rubocop/issues/7389): Fix an issue where passing a formatter might result in an error depending on what character it started with. ([@jfhinchcliffe][])
* [#7397](https://github.com/rubocop-hq/rubocop/issues/7397): Fix extra comments being added to the correction of `Style/SafeNavigation`. ([@rrosenblum][])
* [#7378](https://github.com/rubocop-hq/rubocop/pull/7378): Fix heredoc edge cases in `Layout/EmptyLineAfterGuardClause`. ([@gsamokovarov][])
* …
> Update to Rubocop 0.75.1

- tasks/cops_documentation.rake
This is lifted from the rubocop-rspec work here https://github.com/rubocop-hq/rubocop-rspec/pull/829/files
> Fix docs updater script to work with Rubocop 0.75+

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/partial_search_helper_usage.rb
- spec/rubocop/cop/chef/deprecation/partial_search_helper_usage_spec.rb
> Add ChefDeprecations/PartialSearchHelperUsage

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/search_uses_positional_parameters.rb
- spec/rubocop/cop/chef/deprecation/search_uses_positional_parameters_spec.rb
This detects position parameters and includes autocorrection, which also removes the legacy sort field.
> Add ChefDeprecations/SearchUsesPositionalParameters:

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/partial_search_class_usage.rb
- lib/rubocop/cop/chef/deprecation/partial_search_helper_usage.rb
- lib/rubocop/cop/chef/deprecation/search_uses_positional_parameters.rb
- spec/rubocop/cop/chef/deprecation/partial_search_class_usage_spec.rb
- spec/rubocop/cop/chef/deprecation/partial_search_helper_usage_spec.rb
This detects direct usage of the PartialSearch class, which far too many people did.
> Add ChefDeprecations/PartialSearchClassUsage

- lib/rubocop/cop/chef/modernize/build_essential.rb
I clearly forgot to update this after copying the original cop.
> Fix the description of ChefModernize/UseBuildEssentialResource

- lib/rubocop/cop/chef/modernize/respond_to_metadata.rb
- spec/rubocop/cop/chef/modernize/respond_to_metadata_spec.rb
This is less common, but some people did this in their metadata and we should clean it up. I didn't think it warranted creating another cop so I just extended the existing cop.
> RespondToInMetadata: Catch if defined in metadata as well

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/comments_default_copyright.rb
Yep there's no specs. Something about how the comment parsing works does not work with the spec setup. :shrug:
> Add ChefStyle/DefaultCopyrightComments

- lib/rubocop/cop/chef/style/use_platform_helpers.rb
- spec/rubocop/cop/chef/style/use_platform_helpers_spec.rb
We should catch the != scenario as well
Fixed https://github.com/chef/cookstyle/issues/383
> Autocorrect node['platform'] != to platform?() helpers

- lib/rubocop/cop/chef/modernize/respond_to_metadata.rb
- spec/rubocop/cop/chef/modernize/respond_to_metadata_spec.rb
I think this is an edge case, but we have one in chef_client_updater and
the crash was bugging me.
> Handle non modifier if statements in ChefModernize/RespondToInMetadata

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/resource_with_nothing_action.rb
- lib/rubocop/cop/chef/correctness/unnecessary_name_property.rb
- spec/rubocop/cop/chef/correctness/resource_with_nothing_action_spec.rb
- spec/rubocop/cop/chef/correctness/unnecessary_name_property_spec.rb
Detect defining the nothing action in a resource when that doesn't do anything.
> Add ChefCorrectness/ResourceWithNothingAction cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/effortless/berksfile.rb
Identifies cookbooks that are still using Berkshelf for depsolving
> Add ChefEffortless/Berksfile

- lib/cookstyle.rb
- lib/rubocop/monkey_patches/comment_config.rb
- spec/rubocop/monkey_patches/cookstyle_comment_spec.rb
It seems weird to have a tool named Cookstyle that is controlled with Rubocop comments.
Now you can do this:
```ruby
node.normal['something']['something'] # cookstyle: disable ChefCorrectness/NodeNormal
```
> Allow # cookstyle comments in addition to # rubocop comments

- README.md
Link to the blog post that spells out why we're not working on
Foodcritic anymore.
> Add Cookstyle vs. Foodcritic section

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/unnecessary_mixlib_shellout_require.rb
- spec/rubocop/cop/chef/modernize/unnecessary_mixlib_shellout_require_spec.rb
Just simplify things a bit. No need for this.
> Add ChefModernize/UnnecessaryMixlibShelloutRequire

- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
For some reason a lot of people used both the DSL and the old intializer
method. We need to handle that and avoid double DSL usage
> DefaultActionFromInitialize: don't insert dupe default_action

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/legacy_notify_syntax.rb
- spec/rubocop/cop/chef/deprecation/legacy_notify_syntax_spec.rb
We had this in Foodcritic already so there aren't a ton of them, but we should catch them and nuke them from orbit
> Add ChefDeprecations/LegacyNotifySyntax

- lib/cookstyle.rb
- lib/rubocop/monkey_patches/json_formatter.rb
This allows us to generate chef-analyze reports which tell users how
many issues can be automatically corrected by Cookstyle.
We need to remove this after
https://github.com/rubocop-hq/rubocop/pull/7514 is merged, released and
we pin to that version of Rubocop.
https://github.com/rubocop-hq/rubocop/pull/7514
> Adding correctable info to json formatter

- RELEASE_NOTES.md
- config/cookstyle.yml
> Add Cookstyle 5.13 notes

- lib/rubocop/cop/chef/deprecation/run_command_helper.rb
- spec/rubocop/cop/chef/deprecation/run_command_helper_spec.rb
This makes it so we catch the require / include parts as well, which if
not removed will cause chef-client to fail
> Expand ChefDeprecations/UsesRunCommandHelper to catch more cases

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/attribute_metadata.rb
- lib/rubocop/cop/chef/modernize/conflicts_metadata.rb
- lib/rubocop/cop/chef/modernize/long_description_metadata.rb
- lib/rubocop/cop/chef/modernize/provides_metadata.rb
- lib/rubocop/cop/chef/modernize/recipe_metadata.rb
- lib/rubocop/cop/chef/modernize/replaces_metadata.rb
- lib/rubocop/cop/chef/modernize/respond_to_resource_name.rb
- lib/rubocop/cop/chef/modernize/suggests_metadata.rb
- spec/rubocop/cop/chef/modernize/attribute_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/conflicts_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/long_description_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/provides_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/recipe_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/replaces_metadata_spec.rb
- spec/rubocop/cop/chef/modernize/suggests_metadata_spec.rb
These cops really aren't deprecations. They're just not necessary
anymore. We shouldn't be alerting in chef-analyze that every customer
needs to drop everything and remove long_description from their
metadata. It doesn't warrant that, but if they're already in a cookbook
they should def clean it up.
> Move the metadata cops to ChefModernize

- lib/rubocop/cop/chef/modernize/berksfile_source.rb
- spec/rubocop/cop/chef/modernize/berksfile_source_spec.rb
This is the original Berksfile syntax that was basically just the Cheffile.
> Update ChefModernize/LegacyBerksfileSource to detect REALLY old configs

- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
This is actually wrong, but I found at least one cookbook that's doing it. One more reason that HWRPs were terrible.
> Detect @default_action in the initializer as well

- lib/rubocop/cop/chef/modernize/resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/modernize/resource_with_allowed_actions_spec.rb
Let's not touch poise resources. They have their own syntax
> Don't detect poise resources in CustomResourceWithAllowedActions

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/allowed_actions_initializer.rb
- lib/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/modernize/allowed_actions_initializer_spec.rb
- spec/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions_spec.rb
Don't remove them if we're not in a custom resource
Consider the custom resource cop to be ChefRedundant since there has never been a need for this code in a custom resource. It's just leftover redundant junk
Add a new cop ChefModernize/AllowedActionsFromInitialize that pulls the allowed_actions out of initialize methods in HWRPs. This gets folks closer to LWRPs which gets them closer to custom resources
> Rework how we autocorrect allowed actions

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/foodcritic_comments.rb
- spec/rubocop/cop/chef/modernize/foodcritic_comments_spec.rb
These are no longer necessary when a user has migrated to Cookstyle. This cop will be disabled for now, but sometime in the future we'll probably want to enable it.
> Add a cop for removing legacy Foodcritic comments

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/ruby_block_create_action.rb
- spec/rubocop/cop/chef/deprecation/ruby_block_create_action_spec.rb
The :create action has been replaced with the :run action.
> Add ChefDeprecations/RubyBlockCreateAction cop

- config/cookstyle.yml
- lib/rubocop/chef/cookbook_helpers.rb
- lib/rubocop/cop/chef/correctness/notifies_action_not_symbol.rb
- lib/rubocop/cop/chef/deprecation/legacy_notify_syntax.rb
- spec/rubocop/chef/cookbook_helpers_spec.rb
- spec/rubocop/cop/chef/correctness/notifies_action_not_symbol_spec.rb
- spec/rubocop/cop/chef/deprecation/legacy_notify_syntax_spec.rb
Updates our property helper to accept an array of helpers, which allows updating ChefCorrectness/NotifiesActionNotSymbol and ChefDeprecations/LegacyNotifySyntax to work with both notify and subscribes properties.
> Support checking both notifies and subscribes properties in cops

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/name_property_and_default.rb
- lib/rubocop/cop/chef/modernize/property_with_name_attribute.rb
- lib/rubocop/cop/chef/redundant/unnecessary_name_property.rb
- spec/rubocop/cop/chef/deprecation/name_property_and_default_spec.rb
- spec/rubocop/cop/chef/modernize/property_with_name_attribute_spec.rb
- spec/rubocop/cop/chef/redundant/unnecessary_name_property_spec.rb
- Greatly simplify these cops by using the node matchers so we don’t have to do a pile of defensive coding to traverse hashes and what not. This also most likely makes these cops much more reliable in funky real-world situations.
- Only match on ruby files in libraries/resources. No need to check methods in providers.
- Add autocorrecting to NamePropertyWithDefaultValue. Just delete the default value since that's what the user will do anyways
- Match on attributes as well in NamePropertyWithDefaultValue. This makes sense to do in the LWRP world as well
- Make UnnecessaryNameProperty also match on attributes. Again this is a valid offense in the LWRP world as well
> Improve the cops that check properties / attributes

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/use_platform_helpers.rb
- spec/rubocop/cop/chef/style/use_platform_helpers_spec.rb
```%w(rhel suse).include?(node['platform_family'])```
becomes
```platform_family?('rhel', 'suse')```
> Detect additional ways of checking platform / platform_family with node data

- config/cookstyle.yml
I think once we upgrade to the latest version of rubocop we can do this better with YAML templating, but for now, it's semi-manual.
> Speed up Cookstyle by excluding more files

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/execute_sc_exe.rb
- lib/rubocop/cop/chef/modernize/execute_sleep.rb
- lib/rubocop/cop/chef/modernize/sc_windows_resource.rb
- lib/rubocop/cop/chef/redundant/sensitive_property_in_resource.rb
- lib/rubocop/cop/chef/redundant/unnecessary_desired_state.rb
- lib/rubocop/cop/chef/style/true_false_resource_properties.rb
- spec/rubocop/cop/chef/modernize/execute_sc_exe_spec.rb
- spec/rubocop/cop/chef/modernize/execute_sleep_spec.rb
- spec/rubocop/cop/chef/modernize/sc_windows_resource_spec.rb
- spec/rubocop/cop/chef/redundant/sensitive_property_in_resource_spec.rb
- spec/rubocop/cop/chef/redundant/unnecessary_desired_state_spec.rb
- spec/rubocop/cop/chef/style/true_false_resource_properties_spec.rb
Doing this in a single PR avoids the merge conflicts in the cookstyle.yml file.
ChefStyle/TrueFalseResourceProperties
ChefModernize/ExecuteScExe
ChefModernize/WindowsScResource
ChefModernize/ExecuteSleep
ChefRedundantCode/UnnecessaryDesiredState
> Add 5 new cops for the 5.16 release

- lib/rubocop/cop/chef/style/use_platform_helpers.rb
- spec/rubocop/cop/chef/style/use_platform_helpers_spec.rb
['rhel', some_variable].include?(node['platform_family'] is valid and we
should handle it all correctly without added or double quotes
> Handle additional scenarios of platform checks

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/includes_mixin_shellout.rb
- spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb
The PowerShell mixin was also added by default in Chef Infra 12.4
> Add Powershell mixins to ChefModernize/IncludingMixinShelloutInResources

- config/cookstyle.yml
- lib/rubocop/cop/chef/redundant/apt_repository_distribution_default.rb
- lib/rubocop/cop/chef/redundant/apt_repository_notifies_apt_update.rb
- spec/rubocop/cop/chef/redundant/apt_repository_distribution_default_spec.rb
- spec/rubocop/cop/chef/redundant/apt_repository_notifies_apt_update_spec.rb
Simplify apt_repository usage by removing two complex bits of code that aren't needed.
> Add 2 new cops for removing redundant config in apt_repository

- lib/cookstyle.rb
require_relative is significantly faster and should be used when available.
> Substitute require for require_relative

- .expeditor/verify.pipeline.yml
- .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
- .github/lock.yml
- tasks/cops_documentation.rake
Test on the final release of Ruby 2.7
Fix formatting in our github templates
Fix an error message in Rake to be cookstyle not chefstyle
Remove the github lock config
> Test on Ruby 2.7 + other minor testing updates

- lib/rubocop/cop/chef/style/true_false_resource_properties.rb
- spec/rubocop/cop/chef/style/true_false_resource_properties_spec.rb
We want to fix this in both LWRPs and custom resources. Make sure we catch both. It's a bit tricky due to the kind_of: hash mess.
> Match on attributes in TrueClassFalseClassResourceProperties

- config/cookstyle.yml
This way we exclude them in a mono-repo and in test cookbooks. This not only prevents us from cookstyling people's non-chef ruby code, but it speeds up the cookstyle run since we're touching less.
> Better exclude the files / vendor directories

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/compile_time_resources.rb
- spec/rubocop/cop/chef/modernize/compile_time_resources_spec.rb
This detects overly complex logic for forcing certain resources to run at compile_time
> Add ChefModernize/ResourceForcingCompileTime

- lib/rubocop/cop/chef/redundant/attribute_metadata.rb
- lib/rubocop/cop/chef/redundant/conflicts_metadata.rb
- lib/rubocop/cop/chef/redundant/provides_metadata.rb
- lib/rubocop/cop/chef/redundant/recipe_metadata.rb
- lib/rubocop/cop/chef/redundant/replaces_metadata.rb
- lib/rubocop/cop/chef/redundant/suggests_metadata.rb
- spec/rubocop/cop/chef/redundant/attribute_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/conflicts_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/provides_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/recipe_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/replaces_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/suggests_metadata_spec.rb
This was already applied to long_description and it works great there. This way we don't end up with funky leftover lines that other cops or humans have to clean up.
example leftover lines:
```
```
> Update metadata.rb cops to not leave empty lines behind

- lib/rubocop/cop/chef/redundant/long_description_metadata.rb
- spec/rubocop/cop/chef/redundant/long_description_metadata_spec.rb
This is somewhat common and our current autocorrect results in invalid ruby as it leaves behind the heredoc body and anchor.
> Properly cleanup heredoc long_description metadata

- config/cookstyle.yml
- lib/rubocop/cop/chef/redundant/provides_metadata.rb
- lib/rubocop/cop/chef/redundant/recipe_metadata.rb
- lib/rubocop/cop/chef/redundant/replaces_metadata.rb
- lib/rubocop/cop/chef/redundant/suggests_metadata.rb
- spec/rubocop/cop/chef/redundant/attribute_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/conflicts_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/provides_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/recipe_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/replaces_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/suggests_metadata_spec.rb
Neither right or left gets it all and :both mangles the world. Left seems to result in better output when the metadata is nested between other metadata which is the most common scenario. I updated the specs to reflect a real metadata.rb file.
> Better trim metadata.rb whitespace

- lib/rubocop/cop/chef/style/file_mode.rb
- spec/rubocop/cop/chef/style/file_mode_spec.rb
That way we don't have to rely on the quoting cops fixing it afterward
> Fix ChefStyle/FileMode to autocorrect single quotes

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/overly_complex_supports_depends_metadata.rb
- spec/rubocop/cop/chef/style/overly_complex_supports_depends_metadata_spec.rb
Make Chef a bit easier to read for new users by removing some Ruby where it's not helpful. DRY isn't always better.
> Add ChefStyle/OverlyComplexSupportsDependsMetadata

- docs/cops_chefsharing.md
- lib/rubocop/cop/chef/sharing/invalid_license_string.rb
- spec/rubocop/cop/chef/sharing/invalid_license_string_spec.rb
Add Clarity to License Strings
This commit adds clarity to the documentation for license strings, it
also adds autocorrection for "UNLICENSED" as the top google result is: https://softwareengineering.stackexchange.com/questions/285885/which-spdx-license-is-equivalent-to-all-rights-reserved
Added tests as well to ensure "all rights reserved" will always pass the
check
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
> Add clarity to License Strings

- lib/rubocop/cop/chef/deprecation/user_supports_property.rb
- spec/rubocop/cop/chef/deprecation/user_supports_property_spec.rb
Make sure we don't fail if using string-based hash rockets.
> Additional fixes for ChefDeprecations/UserDeprecatedSupportsProperty

- lib/rubocop/cop/chef/modernize/allowed_actions_initializer.rb
- spec/rubocop/cop/chef/modernize/allowed_actions_initializer_spec.rb
+= usage of @alllowed_actions is valid and can't be replaced with the allowed_actions method call
> Fix false positives in ChefModernize/AllowedActionsFromInitialize

- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
Use node matchers here instead of helper methods.
> Avoid false positives in ChefModernize/DefaultActionFromInitialize

- lib/rubocop/cop/chef/modernize/execute_sysctl.rb
- spec/rubocop/cop/chef/modernize/execute_sysctl_spec.rb
I've noticed a good number of folks that are using the full path when
they shell out. We should alert on those as well.
> Catch shelling out to sysctl when using the full path

- lib/rubocop/cop/chef/deprecation/chef_handler_supports.rb
- spec/rubocop/cop/chef/deprecation/chef_handler_supports_spec.rb
If the hash is surrounded with { } then the autocorrect will produce invalid Ruby code. We now nuke those to autocorrect to the bare hash.
> Fix autocorrection failures in ChefDeprecations/ChefHandlerUsesSupports

- config/cookstyle.yml
This way people can use Cookstyle as part of the migration off Chef 12
without breaking cookbooks by introducing Ruby 2.3isms too early.
Chef 12.14+ are Ruby 2.3.
> Set the target ruby version to 2.3 to support Chef 12

- lib/cookstyle.rb
- lib/rubocop/chef/autocorrect_helpers.rb
- lib/rubocop/cop/chef/redundant/attribute_metadata.rb
- lib/rubocop/cop/chef/redundant/grouping_metadata.rb
- lib/rubocop/cop/chef/redundant/long_description_metadata.rb
- lib/rubocop/cop/chef/redundant/recipe_metadata.rb
- spec/rubocop/cop/chef/redundant/grouping_metadata_spec.rb
- spec/rubocop/cop/chef/redundant/recipe_metadata_spec.rb
There's a few of these on the supermarket. We should properly support this by extracting the logic I added to long_description into a helper.
> Make sure metadata cops properly autocorrect heredocs

- lib/rubocop/cop/chef/style/use_platform_helpers.rb
- spec/rubocop/cop/chef/style/use_platform_helpers_spec.rb
This is another overly complex form of checking platforms that we can convert to use a platform? or platform_family? helpers.
> Expand ChefStyle/UsePlatformHelpers to also detect node['platform'].eql?

- lib/rubocop/cop/chef/sharing/invalid_license_string.rb
Another one we should auto correct
> Autocorrect 'apache v2' to 'Apache-2.0'

- lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb
- spec/rubocop/cop/chef/deprecation/windows_task_change_action_spec.rb
Make sure it responds to value before trying to access that.
Fixed #519 
> Don't fail ChefDeprecations/WindowsTaskChangeAction with a non-string action

- lib/rubocop/cop/chef/deprecation/yum_dnf_compat_recipe.rb
- spec/rubocop/cop/chef/deprecation/yum_dnf_compat_recipe_spec.rb
If there's an inline conditional nuke the conditional as well during the autocorrect. If the conditional isn't inline leave it behind. This prevents the autocorrect from resulting in invalid ruby.
> Fix IncludingYumDNFCompatRecipe to not break with inline conditionals

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/simplify_apt_ppa_setup.rb
- lib/rubocop/cop/chef/redundant/property_splat_regex.rb
- lib/rubocop/cop/chef/redundant/string_property_with_nil_default.rb
- spec/rubocop/cop/chef/modernize/simplify_apt_ppa_setup_spec.rb
- spec/rubocop/cop/chef/redundant/property_splat_regex_spec.rb
- spec/rubocop/cop/chef/redundant/string_property_with_nil_default_spec.rb
StringPropertyWithNilDefault
PropertySplatRegex
SimplifyAptPpaSetup
> Add 3 new cops

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/unnecessary_os_check.rb
- spec/rubocop/cop/chef/style/unnecessary_os_check_spec.rb
Detect when we can simplify a node['os'] check to use platform_family?() instead. This works on everything, but 'linux' which doesn't map to a platform_family.
> Add new ChefStyle/UnnecessaryOSCheck cop

- .expeditor/run_linux_tests.sh
- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/use_require_relative.rb
- spec/rubocop/cop/chef/modernize/use_require_relative_spec.rb
This catches one particular require scenario that should be
require_relative. There's more, but this is a start. We can always
expand this cop later to catch more of them.
> Add ChefModernize/UseRequireRelative

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/node_init_package.rb
- spec/rubocop/cop/chef/modernize/node_init_package_spec.rb
This reduces some crazy complex code that hasn't been necessary since
Chef 12.0.
> Use node['init_package'] to detect systemd

- lib/rubocop/cop/chef/style/true_false_resource_properties.rb
- spec/rubocop/cop/chef/style/true_false_resource_properties_spec.rb
It turns out that we can't use true/false in an attribute. Only properties can do that.
> Revert "Match on attributes in TrueClassFalseClassResourceProperties"

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/windows_registry_uac.rb
- spec/rubocop/cop/chef/modernize/windows_registry_uac_spec.rb
Detect when someone should use the windows_uac resource instead of manually setting registry values.
> Add ChefModernize/WindowsRegistryUAC cop

- lib/rubocop/cop/chef/modernize/execute_apt_update.rb
- spec/rubocop/cop/chef/modernize/execute_apt_update_spec.rb
Detect any execute resource that runs 'apt-get update' and also detect any resource that notifies 'execute[apt-get update]'.
> Detect more apt-get update scenarios

- config/cookstyle.yml
- lib/rubocop/chef/cookbook_only.rb
Neither of these impact how Chef Infra operates and neither can be autocorrected. These alerts require significant cookbook refactor time with little benefit. We have discussed turning this off in the chef-infra slack channel.
> Disable Naming/MethodName and Naming/VariableName

- config/cookstyle.yml
Can't be autocorrected
Doesn't result in a huge amount of value when changed
> Disable the Naming/PredicateName

- lib/rubocop/cop/chef/redundant/unnecessary_name_property.rb
- spec/rubocop/cop/chef/redundant/unnecessary_name_property_spec.rb
This wasn't detecting the kind_of so it wasn't actually working.
> Update ChefRedundant/UnnecessaryNameProperty to detect attributes

- lib/rubocop/cop/chef/modernize/default_action_initializer.rb
- spec/rubocop/cop/chef/modernize/default_action_initializer_spec.rb
The previous code wouldn't work if there was anything in the initialize def after the @action variable.
> Update DefaultActionFromInitialize to not care about variable order

- config/cookstyle.yml
This was a copy/paste error when adding this cop. It should be enabled
by default.
> Enable ChefStyle/UnnecessaryOSCheck

- lib/rubocop/cop/chef/correctness/dnf_package_allow_downgrades.rb
- spec/rubocop/cop/chef/correctness/dnf_package_allow_downgrades_spec.rb
The solution here is just to remove the property.
> Add autocorrection to ChefCorrectness/DnfPackageAllowDowngrades

- lib/rubocop/cop/chef/modernize/powershell_guard_interpreter.rb
Turns out this is all over, not just on powershell_script. Let's get all of them.
> Update ChefModernize/PowerShellGuardInterpreter to look at all resources

- lib/rubocop/cop/chef/modernize/windows_registry_uac.rb
- spec/rubocop/cop/chef/modernize/windows_registry_uac_spec.rb
It can be HKLM which is pretty common.
> Detect the short form the of registry key in ChefModernize/WindowsRegistryUAC

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/powershell_delete_file.rb
- spec/rubocop/cop/chef/correctness/powershell_delete_file_spec.rb
Use file/directory resources to remove files and directories not a
powershell_script. It's slow and not idempotent unless you add your own
conditional.
> Add ChefCorrectness/PowershellScriptDeleteFile

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/databag_helpers.rb
- spec/rubocop/cop/chef/modernize/databag_helpers_spec.rb
This is an old Foodcritic rule that didn't make it over to Cookstyle. Super easy to autocorrect and simplifies codebases a lot.
> Add ChefModernize/DatabagHelpers

- lib/rubocop/chef/cookbook_helpers.rb
- lib/rubocop/cop/chef/deprecation/chef_handler_supports.rb
- lib/rubocop/cop/chef/modernize/powershell_guard_interpreter.rb
- lib/rubocop/cop/chef/redundant/apt_repository_distribution_default.rb
- spec/rubocop/chef/cookbook_helpers_spec.rb
- spec/rubocop/cop/chef/modernize/powershell_guard_interpreter_spec.rb
This fixes the ChefModernize/PowerShellGuardInterpreter cop to detect
the powershell interp being set in powershell_script and batch
resources. Originally we did just powershell_script and then I
incorrectly opened it up all the way (never released). After some
digging it looks like only these 2 resources should have this
removed. That required updates to the helper so we could pass in Arrays
of resource types.
> Allow arrays in match_property_in_resource and fix powershell interp cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/chef_windows_platform_helper.rb
- spec/rubocop/cop/chef/deprecation/chef_windows_platform_helper_spec.rb
This gets us off this old windows helper and onto platform? which we can
update to be just windows? sometime later down the line.
> Add ChefDeprecations/ChefWindowsPlatformHelper cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/powershell_cookbook_helpers.rb
- spec/rubocop/cop/chef/deprecation/powershell_cookbook_helpers_spec.rb
Detect using these deprecated helpers. We can move people to the chef-utils helpers later on.
> Add ChefDeprecations/PowershellCookbookHelpers

- lib/rubocop/cop/chef/modernize/powershell_install_windowsfeature.rb
- spec/rubocop/cop/chef/modernize/powershell_install_windowsfeature_spec.rb
This feature was introduced in 14.0. The description said 15 and the target_chef_version was set to 13. No clue how that happened, but it's wrong.
> Fix chef infra version in PowershellInstallWindowsFeature

- config/cookstyle.yml
- lib/rubocop/cop/chef/sharing/include_property_descriptions.rb
- lib/rubocop/cop/chef/sharing/include_resource_descriptions.rb
- spec/rubocop/cop/chef/sharing/include_property_descriptions_spec.rb
- spec/rubocop/cop/chef/sharing/include_resource_descriptions_spec.rb
These are off by default, but allow us to enforce descriptions in our repos.
> Add cops for resource / property descriptions

- RELEASE_NOTES.md
> Add Cookstyle 6.1 release notes

- config/disable_all.yml
- config/upstream.yml
- lib/cookstyle/version.rb
This release fixes several bugs I discovered while scanning cookbooks on the supermarket and also adds support to several cops for Ruby 2.7 syntax.
> Update RuboCop to 0.81

- lib/rubocop/cop/chef/deprecation/depends_partial_search.rb
- lib/rubocop/cop/chef/deprecation/deprecated_yum_repository_properties.rb
- lib/rubocop/cop/chef/deprecation/launchd_deprecated_hash_property.rb
- lib/rubocop/cop/chef/deprecation/verify_property_file_expansion.rb
- lib/rubocop/cop/chef/deprecation/windows_task_change_action.rb
Some deprecations just require behavior changes. Others require you to
use functionality that might not be there depending on what version of
Chef Infra Client you use. These cops will break on older versions of
chef-client and these version gates make the stepped upgrade process
with Cookstyle easier.
> Add Chef version constraints to multiple deprecation cops

- lib/rubocop/cop/chef/modernize/whyrun_supported_true.rb
- spec/rubocop/cop/chef/modernize/whyrun_supported_true_spec.rb
This extends the cop to detect a common typo of the method name
> Improve ChefModernize/WhyRunSupportedTrue to detect a common typo

- lib/rubocop/cop/chef/deprecation/log_resource_notifications.rb
- spec/rubocop/cop/chef/deprecation/log_resource_notification_spec.rb
It's important that people know when this became available and to allow users to avoid this notification if they're not targeting a modern chef infra client release.
> Improve the LogResourceNotifications to tell when notify_group was introduced

- lib/rubocop/cop/chef/redundant/sensitive_property_in_resource.rb
- spec/rubocop/cop/chef/redundant/sensitive_property_in_resource_spec.rb
> Fix typo in ChefRedundantCode/SensitivePropertyInResource warning

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/deprecated_shellout_methods.rb
- spec/rubocop/cop/chef/deprecation/deprecated_shellout_methods_spec.rb
This will need to autocorrect eventually, but we should get this cop out asap to help with upgrades to Infra 15.
> Add ChefDeprecations/DeprecatedShelloutMethods cop

- lib/rubocop/cop/chef/correctness/node_normal.rb
- lib/rubocop/cop/chef/correctness/node_normal_unless.rb
- lib/rubocop/cop/chef/style/overly_complex_supports_depends_metadata.rb
MLA says don't do this anymore.
> Remove double spaces after periods in documentation

- config/cookstyle.yml
Foodcritic is officially EOL at this point. If folks want to continue to
use both they can disable this in a .rubocop.yml file
> Enable ChefModernize/FoodcriticComments by default

- Rakefile
- config/disable_all.yml
- config/upstream.yml
- lib/cookstyle/version.rb
This release adds a bunch of new autocorrects to help our users fix their code warnings automatically. It also resolves a bunch of bugs that would have impacted autocorrections.
> Update RuboCop to 0.83

- .rubocop.yml
- lib/rubocop/cop/chef/deprecation/user_supports_property.rb
- spec/rubocop/cop/chef/deprecation/user_supports_property_spec.rb
This was broken chef code, but it blew up cookstyle and we need to not explode when we hit bad code.
> Support an edge case where the supports / manage_home value is a method

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/ruby_27_keyword_argument_warnings.rb
- spec/rubocop/cop/chef/deprecation/ruby_27_keyword_argument_warnings_spec.rb
Avoid a common and easy to fix Ruby 2.7 warning
> Add ChefDeprecations/Ruby27KeywordArgumentWarnings cop

- RELEASE_NOTES.md
> Add Cookstyle 6.5 release notes

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/shell_out_helper.rb
- spec/rubocop/cop/chef/modernize/shell_out_helper_spec.rb
Switch people over to the shell_out helper instead of using the more
complex Mixlib::ShellOut
> Add new ChefModernize/ShellOutHelper cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/lazy_eval_node_attribute_defaults.rb
- spec/rubocop/cop/chef/correctness/lazy_eval_node_attribute_defaults_spec.rb
Catch default values in properties that are node attributes
> Add new ChefCorrectness/LazyEvalNodeAttributeDefaults cop

- lib/rubocop/chef/platform_helpers.rb
If someone is mixing up platform and platform family this one comes up a lot.
> Add oracle as an invalid platform_family

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/openssl_password_helpers.rb
- spec/rubocop/cop/chef/correctness/openssl_password_helpers_spec.rb
Detect usage of the old helper that generates a password for users.
> Add new ChefCorrectness/OpenSSLPasswordHelpers cop

- lib/rubocop/cop/chef/modernize/use_multipackage_installs.rb
- spec/rubocop/cop/chef/modernize/use_multipackage_installs_spec.rb
The majority of packages were being missed:
The old cop detected this:
```ruby
case node['platform']
when 'ubuntu'
%w(bmon htop vim curl).each do |pkg|
package pkg do
action :install
end
end
end
```
But not this:
```ruby
case node['platform']
when 'ubuntu'
%w(bmon htop vim curl).each do |pkg|
package pkg
end
end
```
> Detect package installs w/o an action in the multipackage cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/invalid_platform_family_values_in_case.rb
- lib/rubocop/cop/chef/correctness/invalid_platform_values_in_case.rb
- spec/rubocop/cop/chef/correctness/invalid_platform_family_values_in_case_spec.rb
- spec/rubocop/cop/chef/correctness/invalid_platform_values_in_case_spec.rb
This time let's catch them in case statements. There's some code reuse
in these cops, but it's actually a lot simpler to just write it as two
cops vs. trying to create a unified cop.
> Add new cops for incorrect platforms / platform families

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/includes_mixin_shellout.rb
- spec/rubocop/cop/chef/modernize/includes_mixin_shellout_spec.rb
Let's cleanup the HWRPs as well. This is a bit tricky since we need to make sure we don't remove a shellout helper from any old random ruby library. Just the HWRPs where we know we're in a provider class and we'll have them available to us.
> Expand ChefModernize/IncludingMixinShelloutInResources to work in HWRPs

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/resource_uses_only_resource_name.rb
- spec/rubocop/cop/chef/deprecation/resource_uses_only_resource_name_spec.rb
Add the initial part of the detection of resource_name in custom resources
instead of provides.
> Add ChefDeprecations/ResourceUsesOnlyResourceName

- lib/rubocop/cop/chef/deprecation/resource_uses_only_resource_name.rb
- spec/rubocop/cop/chef/deprecation/resource_uses_only_resource_name_spec.rb
> Make sure we autocorrect to both provide and resource_name for Chef < 16

- lib/cookstyle/version.rb
* [#8083](https://github.com/rubocop-hq/rubocop/issues/8083): Fix an error for `Lint/MixedRegexpCaptureTypes` cop when using a regular expression that cannot be processed by regexp_parser gem.
* [#8081](https://github.com/rubocop-hq/rubocop/issues/8081): Fix a false positive for `Lint/SuppressedException` when empty rescue block in `do` block.
* [#8096](https://github.com/rubocop-hq/rubocop/issues/8096): Fix a false positive for `Lint/SuppressedException` when empty rescue block in defs.
* [#8108](https://github.com/rubocop-hq/rubocop/issues/8108): Fix infinite loop in `Layout/HeredocIndentation` auto-correct.
* [#8042](https://github.com/rubocop-hq/rubocop/pull/8042): Fix raising error in `Lint::FormatParameterMismatch` when it handles invalid format strings and add new offense. …
> Update to rubocop 0.85.1

- config/cookstyle.yml
- lib/rubocop/cop/chef/redundant/ohai_attribute_to_string.rb
- spec/rubocop/cop/chef/redundant/ohai_attribute_to_string_spec.rb
There's no reason to .to_s objects that are already strings.
> Add cookstyle cop to detect using .to_s on ohai attribute

- lib/cookstyle.rb
- lib/rubocop/monkey_patches/registry_cop.rb
- spec/rubocop/monkey_patches/migration_departmentname_spec.rb
Cookstyle shouldn't suggest people run rubocop directly even if that would work.
> Monkeypatch the Migration/DepartmentName cop to suggest cookstyle

- config/cookstyle.yml
- lib/rubocop/cop/chef/sharing/include_resource_examples.rb
- spec/rubocop/cop/chef/sharing/include_resource_examples_spec.rb
This is so we can fail our desktop cookbook builds if a PR doesn't includes examples. We're already doing this with resource and property description fields, which works great.
> Add ChefSharing/IncludeResourceExamples

- lib/rubocop/cop/chef/modernize/node_init_package.rb
- spec/rubocop/cop/chef/modernize/node_init_package_spec.rb
Catch using test in a conditional. There's a small number of these on the supermarket. This also migrates the new 0.87+ corrector API, which allowed me to easily have 2 different kinds of offenses autocorrected. Very cool stuff.
> Expand NodeInitPackage to catch more bad systemd tests

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/include_recipe_with_parentheses.rb
- spec/rubocop/cop/chef/style/include_recipe_with_parentheses_spec.rb
Yes it's just a method, but none of our examples show it being called
like a method and reading this code may confuse others later on. Let's
set the style to be bare.
> Add new ChefStyle/IncludeRecipeWithParentheses

- config/cookstyle.yml
- lib/rubocop/cop/chef/modernize/conditional_using_test.rb
- spec/rubocop/cop/chef/modernize/conditional_using_test_spec.rb
Avoid shelling out when we can just use Ruby which is going to be faster.
Fixes https://github.com/chef/cookstyle/issues/543
> Add new cop ChefModernize/ConditionalUsingTest

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
- spec/rubocop/cop/chef/correctness/incorrect_library_injection_spec.rb
1) Detect the .include form of library injection
2) Don't limit this to libraries that injection themselves. There can be library injection anywhere
With this change we detect an additional 230 incorrect library injections on the Supermarket.
> Expand IncorrectLibraryInjection to detect more types of injection

- lib/rubocop/cop/chef/modernize/execute_apt_update.rb
- spec/rubocop/cop/chef/modernize/execute_apt_update_spec.rb
Turns out some people add -y even though you don't need that for an
update.
> Detect additional ways to shellout to apt-get update

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/chefdk_generators.rb
- spec/rubocop/cop/chef/deprecation/chefdk_generators_spec.rb
Fix legacy cookbook generators to work on Chef Workstation
> Add new ChefDeprecations/ChefDKGenerators cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/chef_handler_recipe.rb
- spec/rubocop/cop/chef/deprecation/chef_handler_recipe_spec.rb
We already remove the depends in the metadata and then this would break
users.
> Add ChefDeprecations/ChefHandlerRecipe cop

- config/disable_all.yml
- config/upstream.yml
- lib/cookstyle/version.rb
This adds a bunch of new cops, optimizes the speed / memory usage of
many cops, and includes a large list of bug fixes.
> Bump RuboCop to 0.88

- .expeditor/verify.pipeline.yml
- Gemfile
- bin/cookstyle-profile
- tasks/prof.rake
Adds a binary that we don't ship for profiling cookstyle and adds stackprof and memory_profiler as deps in a new profiling gemfile group.
> Copy over profiling support from RuboCop

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/invalid_default_action.rb
- spec/rubocop/cop/chef/correctness/invalid_default_action_spec.rb
Detect when people are setting it to something that isn't a variable, symbol, or array.
> Add ChefCorrectness/InvalidDefaultAction cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/redundant/double_compile_time.rb
- spec/rubocop/cop/chef/redundant/double_compile_time_spec.rb
This is a weird case I keep seeing that needs to get cleaned up. We can
move the run_action into the compile_time and make it work as expected.
> Add ChefRedundantCode/DoubleCompileTime cop

- WRITING_RULES.md
Update dead links in WRITING_RULES.md to working links.
Signed-off-by: Dan Gordon <chef@dangordon.xyz>
Some of the links in WRITING_RULES.md directed to 404 pages which may make it difficult for users to find helpful information about how to write custom Cookstyle rules.  This commit simply updates the dead links in that file to working ones.
n/a
Note: this change is just updating documentation, which is why I did not run through any of the tests.
> Update dead links

- config/cookstyle.yml
This was never actually used by cookstyle and just came over with rubocop-chef.
> Cleanup leftover config from rubocop-chef project

- config/cookstyle.yml
This way they link to the correct anchors.
> Fix a few incorrect StyleGuide links

- lib/cookstyle.rb
- lib/rubocop/monkey_patches/base.rb
This monkeypatch needs to be on the base class not the cop class now. This allows is to work off the new style cops that inherit from base. The test that this works will be the next cop I'm shipping which previously exploded and runs fine with this patch.
> Fix target_chef_version support in the new Rubocop 0.88+ format of cops

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/macos_userdefaults_invalid_type.rb
- lib/rubocop/cop/chef/deprecation/macos_userdefaults_global_property.rb
- spec/rubocop/cop/chef/correctness/macos_userdefaults_invalid_type_spec.rb
- spec/rubocop/cop/chef/deprecation/macos_userdefaults_global_property_spec.rb
Detect global property which was always broken, but is now deprecated
Detect invalid types which were silently ignored before and now raise
> Add 2 new cops for macos_userdefaults changes in 16.3

- config/cookstyle.yml
- lib/rubocop/cop/chef/style/file_mode.rb
- spec/rubocop/cop/chef/style/file_mode_spec.rb
files_mode exists in the remote_directory resource and should also be a string. I also converted this cop to the new format, improved the warning text, and improved the examples while I was in here.
> Update ChefStyle/FileMode to support files_mode as well

- config/cookstyle.yml
This isn't a thing folks should worry about in cookbooks. There's more
pressing issues.
> Turn off Naming/AccessorMethodName

- lib/rubocop/cop/chef/deprecation/poise_archive.rb
Set PoiseArchive minimum chef version to 15.0.
The `archive_file` syntax is only available from Chef 15+ so the minimum version of the rule has to be adjusted accordingly.
> Set PoiseArchive minimum chef version to 15.0

- config/cookstyle.yml
It's been a while since I audited the RuboCop releases for useful new cops. This enables a few useful ones that have minimal impact on cookbooks. Many of these had zero offenses on the Supermarket since you'd often find the issue while troubleshooting. Others like ArrayCoercion (45 occurrences) and RedundantAssignment (145 occurrences) will have a small impact on the overall Supermarket estate.
> Enable additional cops from recent RuboCop releases

- lib/cookstyle/version.rb
> Update RuboCop engine to 0.89.1

- lib/cookstyle.rb
Requires in ruby are very slow. We patch around this in our omnibus
installs of ruby, but for non-omnibus installs we should avoid requiring
things when we don't need to.
> Optimize requires for non omnibus installs

- Gemfile
- lib/rubocop/cop/chef/deprecation/ruby_27_keyword_argument_warnings.rb
Use Pete's recommendation here and use the new Base class.
> Refactor Ruby27KeywordArgumentWarnings

- lib/rubocop/cop/chef/sharing/include_property_descriptions.rb
- spec/rubocop/cop/chef/sharing/include_property_descriptions_spec.rb
By searching processed_source.ast the cop wouldn't fire if *any* property in the resource had a description. Now it properly requires the property it's looking at the have a description.
> Fix IncludePropertyDescriptions to catch all occurrences

- lib/rubocop/cop/chef/sharing/include_resource_descriptions.rb
- spec/rubocop/cop/chef/sharing/include_resource_descriptions_spec.rb
Remove the str check since it might be a dstr or a method call or anything really.
> Update IncludeResourceDescriptions to allow string interpolation

- lib/rubocop/cop/chef/effortless/berksfile.rb
- lib/rubocop/cop/chef/effortless/data_bags.rb
- lib/rubocop/cop/chef/effortless/node_environment.rb
- lib/rubocop/cop/chef/effortless/node_policygroup.rb
- lib/rubocop/cop/chef/effortless/node_roles.rb
- lib/rubocop/cop/chef/effortless/search_for_environments_or_roles.rb
- lib/rubocop/cop/chef/effortless/search_used.rb
- lib/rubocop/cop/chef/redundant/apt_repository_distribution_default.rb
- lib/rubocop/cop/chef/redundant/apt_repository_notifies_apt_update.rb
- lib/rubocop/cop/chef/redundant/attribute_metadata.rb
- lib/rubocop/cop/chef/redundant/conflicts_metadata.rb
- lib/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions.rb
- lib/rubocop/cop/chef/redundant/grouping_metadata.rb
- lib/rubocop/cop/chef/redundant/long_description_metadata.rb
- lib/rubocop/cop/chef/redundant/multiple_platform_checks.rb
- lib/rubocop/cop/chef/redundant/name_property_and_required.rb
- lib/rubocop/cop/chef/redundant/ohai_attribute_to_string.rb
- lib/rubocop/cop/chef/redundant/property_splat_regex.rb
- lib/rubocop/cop/chef/redundant/property_with_default_and_required.rb
- lib/rubocop/cop/chef/redundant/provides_metadata.rb
- lib/rubocop/cop/chef/redundant/recipe_metadata.rb
- lib/rubocop/cop/chef/redundant/replaces_metadata.rb
- lib/rubocop/cop/chef/redundant/resource_with_nothing_action.rb
- lib/rubocop/cop/chef/redundant/sensitive_property_in_resource.rb
- lib/rubocop/cop/chef/redundant/string_property_with_nil_default.rb
- lib/rubocop/cop/chef/redundant/suggests_metadata.rb
- lib/rubocop/cop/chef/redundant/unnecessary_name_property.rb
- lib/rubocop/cop/chef/redundant/use_create_if_missing.rb
These changes update all cops in the Effortless and Redundant rule sets to the format used in the latest Rubocop versions. This will provide us the flexibility to update Rubocop versions if/when they ever stop supporting the legacy format.
- [ x ] Chore (non-breaking change that does not add functionality or fix an issue)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have run the pre-merge tests locally and they pass.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
- [ x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Effortless and Redundant cops refactor to latest Rubocop format

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/cb_depends_on_self.rb
- spec/rubocop/cop/chef/deprecation/cb_depends_on_self_spec.rb
This is a deprecation necessary to upgrade to Chef Infra Client 13 and we should flag it for folks that are only running the deprecation cops so they can complete their upgrades.
> Move CookbooksDependsOnSelf from ChefCorrectness to ChefDeprecations

- lib/rubocop/cop/chef/correctness/malformed_value_for_platform.rb
- lib/rubocop/cop/chef/deprecation/ use_automatic_resource_name.rb
- lib/rubocop/cop/chef/deprecation/deprecated_windows_version_check.rb
- lib/rubocop/cop/chef/deprecation/easy_install.rb
- lib/rubocop/cop/chef/deprecation/epic_fail.rb
- lib/rubocop/cop/chef/deprecation/erl_call.rb
- lib/rubocop/cop/chef/deprecation/partial_search_helper_usage.rb
- lib/rubocop/cop/chef/deprecation/resource_overrides_provides_method.rb
- lib/rubocop/cop/chef/deprecation/resource_uses_dsl_name_method.rb
- lib/rubocop/cop/chef/deprecation/resource_uses_provider_base_method.rb
- lib/rubocop/cop/chef/deprecation/use_inline_resources.rb
- lib/rubocop/cop/chef/effortless/data_bags.rb
- lib/rubocop/cop/chef/effortless/node_environment.rb
- lib/rubocop/cop/chef/effortless/node_policygroup.rb
- lib/rubocop/cop/chef/effortless/node_roles.rb
- lib/rubocop/cop/chef/effortless/search_for_environments_or_roles.rb
- lib/rubocop/cop/chef/effortless/search_used.rb
- lib/rubocop/cop/chef/modernize/cron_manage_resource.rb
A lot of our cops are just looking for a particular method being used.
We can greatly speed these up with this new feature introduced in
RuboCop 0.90
> Use RESTRICT_ON_SEND to speedup on_send checks

- lib/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions_spec.rb
We need to not alert if the resource lacks actions OR it's a poise
action, not both. Add 2 tests for that.
Signed-off-by: Tim Smith
> Resolve a regression in CustomResourceWithAllowedActions

- lib/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions.rb
- spec/rubocop/cop/chef/redundant/custom_resource_with_allowed_actions_spec.rb
Make sure we trigger on actions, but not something new new_resource.actions
> Resolve another regression in CustomResourceWithAllowedActions

- lib/rubocop/cop/chef/deprecation/resource_overrides_provides_method.rb
- spec/rubocop/cop/chef/deprecation/resource_overrides_provides_method_spec.rb
:facepalm: This is an on_def not an on_send. Add a test to catch this
sort of thing in the future.
> Resolve a regression in ResourceOverridesProvidesMethod

- config/cookstyle.yml
- config/upstream.yml
Something in one of the older RuboCop releases made this always run.
Recently it stopped running and it's one of the most important cops for
detecting invalid code.
> Enable Lint/Syntax cop that previously enabled by default

- Rakefile
It doesn't show up in the task list without this.
> Add missing description to rake task

- bin/cookstyle
- lib/cookstyle.rb
- spec/spec_helper.rb
Avoid using File.dirname(__FILE__) when we can just use __dir__ to get the same thing.
> Replace uses of File.dirname(__FILE__) with __dir__

- lib/rubocop/cop/chef/deprecation/search_uses_positional_parameters.rb
- lib/rubocop/cop/chef/deprecation/windows_feature_servermanagercmd.rb
Avoid a regex where we don't need one
Avoid creating an array object for each argument we parse
> Minor optimizations from rubocop-performance

- spec/spec_helper.rb
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
Followup to #737. Passed tests locally, let's see how CI likes it.
> Remove unused stuff from spec_helper.

- spec/rubocop/chef/cookbook_helpers_spec.rb
- spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb
- spec/rubocop/cop/chef/modernize/node_init_package_spec.rb
- spec/rubocop/cop/chef/modernize/respond_to_resource_name_spec.rb
- spec/rubocop/cop/chef/modernize/simplify_apt_ppa_setup_spec.rb
- spec/rubocop/cop/chef/style/file_mode_spec.rb
Identify some duplicate specs
Stop saying "should"
> Spec cleanup from rubocop-rspec

- lib/rubocop/cop/chef/correctness/incorrect_library_injection.rb
- spec/rubocop/cop/chef/correctness/incorrect_library_injection_spec.rb
This continues some terrible duplicate code, but it works and we have tests. It can be refactored whenever someone wants to deep dive into the rubocop node syntax.
> ChefCorrectness/IncorrectLibraryInjection: Avoid adding duplicate includes in autocorrection

- config/disable_all.yml
- config/upstream.yml
- lib/cookstyle/version.rb
> Update RuboCop to 0.91

- lib/cookstyle.rb
- lib/rubocop/monkey_patches/rescue_ensure_alignment.rb
- spec/rubocop/monkey_patches/rescue_ensure_alignment_spec.rb
This was a bug I reported that sadly didn't make it into the 0.91.0
release
> Backport a fix for Layout/RescueEnsureAlignment

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/property_without_type.rb
- spec/rubocop/cop/chef/correctness/property_without_type_spec.rb
People should really be passing a type in even if they're using some other form of validation later on like a regex
> Add new ChefCorrectness/PropertyWithoutType cop

- lib/rubocop/cop/chef/modernize/respond_to_compile_time.rb
This node match is still terrible and could be greatly improved, but this was our #1 slow spec:
before
```
RuboCop::Cop::Chef::ChefModernize::RespondToCompileTime doesn't register an offense when using just compile_time true
0.45545 seconds ./spec/rubocop/cop/chef/modernize/respond_to_compile_time_spec.rb:75
```
After it's not even on the list and the #10 is now 0.00252 seconds.
> Optimize our slowest cop

- bin/cookstyle
- config/cookstyle.yml
- cookstyle.gemspec
We're disabling things that are already disabled here.
> Enable 3 new ruby cops & remove duplicate disables

- lib/rubocop/cop/chef/style/comments_format.rb
I have no idea what I was thinking here. This is pretty terrible. This was #21 on CPU usage and now it's not in the top 100.
Before:
```
TOTAL    (pct)     SAMPLES    (pct)     FRAME
327   (1.0%)         327   (1.0%)     RuboCop::Cop::Chef::ChefStyle::CommentFormat#invalid_comment?
```
> Run a single regex per comment line instead of 9

- config/upstream.yml
- lib/cookstyle/version.rb
> Update RuboCop to 0.92

- lib/rubocop/cop/chef/deprecation/resource_overrides_provides_method.rb
By adding a ? to the end of the matcher it returns a bool, which reduces the data we have to pass around and makes the comparison simpler.
> Simplify ChefDeprecations/ResourceOverridesProvidesMethod

- lib/rubocop/cop/chef/deprecation/legacy_notify_syntax.rb
This is slightly faster than .dup
> Use + instead of dup to unfreeze a string

- .rubocop.yml
- Gemfile
Make sure we're doing all we can for the perf of the gem.
> Enable rubocop-performance in CI

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/octal_mode_as_string.rb
- spec/rubocop/cop/chef/correctness/octal_mode_as_string_spec.rb
These are not valid and we should call them out.
> Add new ChefCorrectness/OctalModeAsString cop

- Rakefile
- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/use_yaml_dump.rb
- spec/rubocop/cop/chef/deprecation/use_yaml_dump_spec.rb
This works around the issues with autoload and Chef Infra Client 16.5+
> Add ChefDeprecations/UseYamlDump cop

- config/cookstyle.yml
This cop has no autocorrect and there's really no advantage when someone
moves their code to this from the helpers. Really it just makes it
slightly harder to read.
> Disable Style/NumericPredicate

- .expeditor/config.yml
We're not shipping a N-1 release anymore
> Remove the release branch constraints

- config/cookstyle.yml
This probably isn't very common in cookbooks, but if we run into one
it's a great way to reduce complexity.
> Enable Style/CollectionCompact

- lib/rubocop/cop/chef/modernize/use_multipackage_installs.rb
- spec/rubocop/cop/chef/modernize/use_multipackage_installs_spec.rb
Detect when blocks that include more than just the package install. It's pretty common that they also include an apt_update or an include_recipe 'apt' when we're on a debian-ish platform.
I plan to open another PR to refactor the if detection with this same support. baby steps here.
> Handle more multipackage scenarios

- config/cookstyle.yml
[Obvious fix] Parent change causing the need for this change is at https://github.com/chef/cookstyle/commit/af7f38f146c3f57ad83deb0f7308982a99e3f015#diff-46b42b4229cd7a39c564e780bb665a8bde4fdf722007e8473f167fe53ed4b995
Broken URLs in cookstyle.yml
> cookstyle.yml - Update the broken StyleGuideBaseURL values

- config/cookstyle.yml
Signed-off-by: Pete Higgins <pete@peterhiggins.org>
This came up in the PR on chef/chef-server: https://github.com/chef/chef-server/pull/2174/files#r527113845
The warning from this cop led the PR author to change this code:
> Chef::Node.send(:include, ChefOpsDCC::Helpers)
to this syntactically valid but incorrect code:
> Chef::Node.send(include ChefOpsDCC::Helpers)
> Disable cop with potentially misleading warning message.

- Gemfile
We don't need to pin this anymore. They added Ruby 2.4 support back.
> Unpin parallel gem since it supports Ruby 2.4 again

- config/cookstyle.yml
Anything checking a resource should skip the Berksfile and the attributes files
> Exclude more files in our cops to speed them up

- config/cookstyle.yml
It looks like the respond_to is being copied over as folks migrate from LWRPs to custom resources. There are 6 of these on the Supermarket and we might as well correct them while we're scanning for the occurrences in providers.
> Run Chef/Modernize/RespondToProvides in resources as well

- lib/rubocop/cop/chef/style/comment_sentence_spacing.rb
I'm fairly certain this cop was broken.
> Update Chef/Style/CommentSentenceSpacing to use the new RuboCop methods

- config/upstream.yml
- lib/cookstyle/version.rb
- spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb
A bunch of autocorrects have been added as well as some nice bug fixes and hints when cops in configs are wrong.
> Update RuboCop to 1.6.2

- lib/rubocop/cop/chef/redundant/unnecessary_name_property.rb
- spec/rubocop/cop/chef/redundant/unnecessary_name_property_spec.rb
Before the hash has to be in the right order to match. If kind_of is last it wouldn't alert. Now we catch that additional scenario. There are 65 resources that define it that way on Supermarket.
> Update UnnecessaryNameProperty to not care about order

- lib/rubocop/cop/chef/deprecation/legacy_notify_syntax.rb
This was fixed in rubocop-ast so we don't have to get the source anymore
to get the actual string.
https://github.com/rubocop-hq/rubocop-ast/pull/167
> Update dstr handling for new rubocop-ast

- config/cookstyle.yml
This will prevent broken cookbooks in future ruby releases where this
code won't work
> Enable Lint/DeprecatedConstants

- bin/cookstyle
We have documented each cop. This way we link to those docs.
> Always enable the styleguide links to provide better docs

- config/cookstyle.yml
This is causing failures when the begin/end is in a ruby block
> Disable Style/RedundantBegin for now

- lib/rubocop/cop/chef/modernize/windows_registry_uac.rb
Turns out we need to keep the indentation the same here
> Fix indentation in windows_uac causes bad docs generation

- config/cookstyle.yml
As noted in [1], we should ignore anything under the specs folder for this check.
[1] https://github.com/chef/cookstyle/pull/853/files#r632997244
Signed-off-by: Lance Albertson <lance@osuosl.org>
> Ignore specs for Chef/Deprecations/ResourceWithoutUnifiedTrue

- config/cookstyle.yml
With the beginning slash cookstyle will ignore all files if a parent
directory in the current path is named `files` or `vendor`
> Remove beginning slash from exclude path

- config/cookstyle.yml
- lib/cookstyle.rb
- lib/rubocop/cop/inspec/deprecation/attribute_default.rb
- lib/rubocop/cop/inspec/deprecation/attribute_helper.rb
- spec/rubocop/cop/inspec/attribute_default_spec.rb
- spec/rubocop/cop/inspec/attribute_helper_spec.rb
Add new cops for detecting incorrect attribute/input usage in InSpec controls.
Fixes https://github.com/chef/cookstyle/issues/26 and https://github.com/chef/customer-bugs/issues/363 and https://chef.aha.io/ideas/ideas/INSPEC-I-30
> Add new InSpec cops to Cookstyle

- config/cookstyle.yml
- lib/rubocop/cop/chef/deprecation/policyfile_community_source.rb
- spec/rubocop/cop/chef/deprecation/policyfile_community_source_spec.rb
Detect the usage of the old :community source in Policyfiles
> Add new Chef/Deprecations/PolicyfileCommunitySource cop

- config/cookstyle.yml
Resource partials are stored in a cookbook’s /resources directory just like custom resources, but they start with the _ prefix. They should be excluded from Chef/Deprecations/ResourceWithoutUnifiedTrue.
> Ignore resource partials for Chef/Deprecations/ResourceWithoutUnifiedTrue

- lib/rubocop/cop/chef/deprecation/resource_without_unified_mode_true.rb
- spec/rubocop/cop/chef/deprecation/resource_without_unified_mode_true_spec.rb
Exit if the processed AST is nil
> Prevent ResourceWithoutUnifiedTrue fails with empty files

- lib/rubocop/cop/chef/correctness/metadata_missing_name.rb
- spec/rubocop/cop/chef/correctness/metadata_missing_name_spec.rb
Right now MetadataMissingName is firing anytime it scans. This means if
you have a non cookbook project that has a file named metadata.rb and
you use the chef vscode extension that file will be modified just by
opening it up in vscode. This keeps happening to me in omnibus. Convert
this to use native correct calls.
> Fix MetadataMissingName to properly autocorrect

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/powershell_file_exists.rb
- spec/rubocop/cop/chef/correctness/powershell_file_exists_spec.rb
Detect when someone uses PowerShell to see if a file exists on disk.
This is super slow and way more complex/error prone.
> Add new Chef/Correctness/PowershellFileExists cop

- config/cookstyle.yml
- docs-chef-io/data/cookstyle/cops_chef_modernize_unnecessarydependschef14.yml
- lib/rubocop/cop/chef/modernize/chef_15_resources.rb
- lib/rubocop/cop/chef/modernize/depends_kernel_module_cookbook.rb
- lib/rubocop/cop/chef/modernize/depends_locale_cookbook.rb
- lib/rubocop/cop/chef/modernize/depends_timezone_lwrp_cookbook.rb
- lib/rubocop/cop/chef/modernize/depends_windows_firewall_cookbook.rb
- lib/rubocop/cop/chef/modernize/libarchive_file.rb
- spec/rubocop/cop/chef/modernize/chef_14_resources_spec.rb
- spec/rubocop/cop/chef/modernize/chef_15_resources_spec.rb
- spec/rubocop/cop/chef/modernize/depends_kernel_module_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/depends_locale_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/depends_timezone_lwrp_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/depends_windows_firewall_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/libarchive_file_spec.rb
Detect metadata depends for cookbooks in the client itself now.
> Add 5 new cops to detect deprecated cookbooks

- config/cookstyle.yml
- docs-chef-io/data/cookstyle/cops_chef_correctness_powershellfileexists.yml
- lib/rubocop/cop/chef/correctness/powershell_file_exists.rb
- lib/rubocop/cop/chef/deprecation/depends_chef_nginx_cookbook.rb
- lib/rubocop/cop/chef/deprecation/depends_chef_reporting_cookbook.rb
- lib/rubocop/cop/chef/deprecation/depends_omnibus_updater_cookbook.rb
- lib/rubocop/cop/chef/modernize/depends_chef_vault_cookbook.rb
- lib/rubocop/cop/chef/modernize/depends_chocolatey_cookbooks.rb
- lib/rubocop/cop/chef/modernize/depends_openssl_cookbook.rb
- spec/rubocop/cop/chef/correctness/powershell_file_exists_spec.rb
- spec/rubocop/cop/chef/deprecation/depends_chef_nginx_cookbook_spec.rb
- spec/rubocop/cop/chef/deprecation/depends_chef_reporting_cookbook_spec.rb
- spec/rubocop/cop/chef/deprecation/depends_omnibus_updater_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/depends_chef_vault_cookbook_spec.rb
- spec/rubocop/cop/chef/modernize/depends_chocolatey_cookbooks_spec.rb
- spec/rubocop/cop/chef/modernize/depends_openssl_cookbook_spec.rb
Flag more deps that users can nuke from modern Chef Infra installations
> Add 6 more cops to detect deprecated or integrated cookbooks

- lib/rubocop/cop/chef/modernize/use_chef_language_cloud_helpers.rb
- lib/rubocop/cop/chef/modernize/use_chef_language_env_helpers.rb
These should be limited to 15.5+
> Add Chef target versions to existing cops

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/invalid_cookbook_name.rb
- spec/rubocop/cop/chef/correctness/invalid_cookbook_name_spec.rb
Detect cookbook names with a period that may cause internal issues in the client and/or server
> Add new Chef/Correctness/InvalidCookbookName cop

- config/cookstyle.yml
- lib/rubocop/cop/chef/correctness/invalid_notification_resource.rb
- spec/rubocop/cop/chef/correctness/invalid_notification_resource_spec.rb
Detect when people put the quotes in the wrong place. This came up in a bug recently. Running it over all of Supermarket it found one I did wrong too :facepalm:
> Add new Chef/Correctness/InvalidNotificationResource cop

- lib/rubocop/cop/chef/redundant/use_create_if_missing.rb
- spec/rubocop/cop/chef/redundant/use_create_if_missing_spec.rb
If someone uses the name_property of path we want to dig in there as well.
> Add support for the `path` property in RedundantCode/UseCreateIfMissing

- lib/rubocop/chef/cookbook_helpers.rb
- lib/rubocop/cop/chef/redundant/use_create_if_missing.rb
- spec/rubocop/cop/chef/redundant/use_create_if_missing_spec.rb
Also modernize the resource to use the helpers and make sure the helpers support properties with a block. This change identified 150 new offenses on the Supermarket.
> Update UseCreateIfMissing to support non-string path values

- config/cookstyle.yml
Over in https://github.com/rubocop/rubocop/issues/9752 we figured out
that the reason end-users can't enable/disable Cookstyle departments is
because `Enabled` isn't in the config and thus [can't be
overridden](https://github.com/rubocop/rubocop/issues/9752#issuecomment-877707141).
This change will allow a user to not only do the obvious:
```yaml
Chef/Correctness:
Enabled: false
```
But more interestingly do something like this:
```yaml
AllCops:
DisabledByDefault: true
Chef/Correctness:
Enabled: true
```
CC @jonas054
> Allow departments to be enabled/disabled by users

- lib/rubocop/cop/chef/deprecation/deprecated_chefspec_platform.rb
- spec/rubocop/cop/chef/deprecation/deprecated_chefspec_platform_spec.rb
All Amazon 201X releases are deprecated
Fedora 31 is now deprecated
FreeBSD 11.2 is now deprecated
macOS 11.0 has been replaced with macOS 11
Debian 9.12 is now deprecated
CentOS 7.8 is now deprecated
Redhat 7.8 is now deprecated
> Update Chef/Deprecations/DeprecatedChefSpecPlatform for new fauxhai deprecations

- config/upstream.yml
- lib/cookstyle/version.rb
Obvious fix; these changes are the result of automation not creative thinking.
> Vendor rubocop-1.25.1 upstream configuration.

- lib/rubocop/cop/chef/modernize/cron_d_file_or_template.rb
- spec/rubocop/cop/chef/modernize/cron_d_file_or_template_spec.rb
Updates node matcher pattern for `Chef/Modernize/CronDFileOrTempalte` to capture everything in the file/template/cookbook_file resource declaration to catch offenses where the resource name is both a regular string and an interpolated string.
The existing matcher does not flag offenses if the `file`/`cookbook_file`/`template` resource is named using string interpolation
https://github.com/chef/cookstyle/issues/940
~~since i don't use ruby outside of ChefDK, I need to put together a local dev env to run the tests in; doing so currently and will update the Checklist after I've done so and run the tests on my local machine.~~ This has since been completed.
> Flag Chef/Modernize/CronDFileOrTemplate offenses with string interpolation

- lib/rubocop/cop/chef/modernize/cron_d_file_or_template.rb
- spec/rubocop/cop/chef/modernize/cron_d_file_or_template_spec.rb
* updates the node pattern matcher macro to a stricter pattern to simplify its use
* checks the `path` if provided to the resource to cover cases where the path is provided to it and not the name property
https://github.com/chef/cookstyle/issues/943
> Chef/Modernize/CronDFileOrTemplate Improvements

- lib/rubocop/cop/chef/modernize/cron_d_file_or_template.rb
- spec/rubocop/cop/chef/modernize/cron_d_file_or_template_spec.rb
Add a spec for something that should match and simplify the detection a bit to make sure we don't misdetect something
> Fix false positives in CronDFileOrTemplate

- config/cookstyle.yml
- docs-chef-io/assets/cookstyle/cops_chef_deprecations_delivery.yml
- lib/rubocop/cop/chef/deprecation/delivery.rb
- lib/rubocop/monkey_patches/allow_invalid_ruby.rb
- spec/rubocop/cop/chef/deprecation/delivery_spec.rb
Signed-off-by: Doug Knight <doug.knight@karmix.org>
RuboCop inspects files not directories.  In order to report an offense for the existence of a `.delivery` directory, the Delivery cop performs the checks and makes its report when asked to inspect the `metadata.rb` file.  On subsequent runs, RuboCop will see that the content of `metadata.rb` has not changed, and report the cached offense form the Delivery cop, even after the `.delivery` directory is removed.
This patch refactors the Delivery cop to report offenses for the existence of the files `.delivery/config.json` (Chef Delivery config) and  `.delivery/project.toml` (Chef Delivery Local config), instead of trying to check for the existence of a directory.
Fixes #942
> Refactor Chef/Deprecations/Delivery to address caching issues

- .github/workflows/lint.yml
- .github/workflows/unit.yml
- cookstyle.gemspec
- lib/rubocop/cop/chef/modernize/cron_d_file_or_template.rb
The following recipe will raise the CronDFileOrTemplate cop due to the regex matching in the same class.
```ruby
file '/etc/cron.deny' do 
action :delete
end
```
I've updated the regex so that `cron.deny` will no longer treated as a cron file and the current scenarios will work as it is. The samples of the regex are below.
```ruby
3.1.0 :001 > exp = %r{/etc/cron\.d\b}i
=> /\/etc\/cron\.d\b/i
3.1.0 :002 > "/etc/cron.d/".match?(exp)
=> true
3.1.0 :003 > "/etc/cron.d".match?(exp)
=> true
3.1.0 :004 > "/etc/cron.d/backup".match?(exp)
=> true
3.1.0 :005 > "/etc/cron.deny".match?(exp)
=> false
3.1.0 :006 > "/etc/cron.allow".match?(exp)
=> false
```
> [CHEF-1116] - Fixed the false positive issue with CronDFileOrTemplate and Updated the required Ruby version to 2.7

- lib/rubocop/cop/chef/style/comment_sentence_spacing.rb
See
https://github.com/rubocop/rubocop/commit/f8813e76cef5c06cfe1f3a73b032f4f06de7de6c
`location` no longer needed, in the "new" Base API (which came about in RuboCop 0.87). CommentSentenceSpacing is disabled by default, which is how it got missed
> Fix Base API breakage in Chef/Style/CommentSentenceSpacing

- bin/cookstyle
- lib/cookstyle/chefstyle.rb
There's a decent amount of Rake code that uses `require "chefstyle"` to set the defaults for RuboCop (eg
https://github.com/chef/ohai/blob/6d64237f9987c3bf51805e19884e6e710c3a40f6/Rakefile#L19), and rather than doing surgery on each repo's Rakefile, it'd be easier to keep that same behavior for loading the configuration and cops. With this change a migration involving Rake should only involve a Gemfile update and changing `require "chefstyle"` to `require "cookstyle/chefstyle"`.
> Add chefstyle library file for Rake backwards compatibility

- spec/rubocop/cop/chef/modernize/cron_d_file_or_template_spec.rb
#959 fixed the `/etc/cron.deny` bug in #946 and `/etc/cron.daily` bug in #954, but regression tests were missing
> [#946 and #954] Add missing tests

- lib/cookstyle.rb
We need to pass TargetChefVersion into the default config, otherwise the [ConfigValidator#each_invalid_parameter method
complains](https://github.com/rubocop/rubocop/blob/2fee8552c6c8237950d8df7ec857c49f308a6d34/lib/rubocop/config_validator.rb#L198)
> Fix #970: Add extra stub to pass ConfigValidator

- .github/workflows/lint.yml
- .github/workflows/unit.yml
In today's community PR review we discussed how EOL Rubies have been broken on a variety of CI pipelines, gumming up efforts such as fully removing Chefstyle. After discussion with @tpowell-progress / @jaymzh we came up with removing EOL Rubies from repository CIs where there's no hard backwards-compatibility needs (eg mixlib-install).
> [CI] Drop EOL rubies

- Gemfile
- config/chefstyle.yml
- config/cookstyle.yml
- cookstyle.gemspec
- docs-chef-io/assets/cookstyle/cops_chef_deprecations_deprecatedchefspecplatform.yml
- lib/rubocop/cop/chef/deprecation/deprecated_chefspec_platform.rb
- lib/rubocop/cop/chef/deprecation/deprecated_shellout_methods.rb
- lib/rubocop/cop/chef/security/ssh_private_key.rb
- spec/rubocop/cop/chef/deprecation/deprecated_chefspec_platform_spec.rb
Fix the cops broken during one of my upgrades a long time ago. This is probably going to result in CI failures elsewhere as these cops have been disabled for a while. Test Kitchen triggered on one of the alignment cops.
> Fix commented out cops due to renames

- RELEASE_NOTES.md
- config/chefstyle.yml
- config/cookstyle.yml
- lib/cookstyle/version.rb
Enable a new cop that will probably never find anything, but is a good practice for users
> Update to Rubocop 1.81 + enable new cop
